### ISSUE TITLE
User Story: app produces correct measurements

### ISSUE THREAD

**Issue by arne-broering** [enviroCar/enviroCar-app#112]
We need to make sure that the measurements produced by the app and uploaded to the server are correct.

There seem to be wrong fuel consumption / CO2 measurements; see:
https://github.com/enviroCar/enviroCar-www/issues/41

The process of creating the measurements needs to be understood and well documented (also on website).

**Comment by dewall** [comment]
wrong measurements occured due to errornous recording procedures.
