### ISSUE TITLE
Create tracks dynamically in case of certain events...

### ISSUE THREAD

**Issue by jakobmoellers** [enviroCar/enviroCar-app#12]
New track if last measurement is more than x minutes/hours ago (save last measurement time in shared prefs or take it from the internal database?)

New track if user clicks on create new track button

new track if last position is significantly different from the current position (save last measurement in shared prefs or take it from the internal database?)

New track if old track is uploaded and no current track is available in the database

new track if VIN changed

**Comment by dewall** [comment]
not relevant anymore
