### ISSUE TITLE
Extended Sensor Metadata

### ISSUE THREAD

**Issue by nuest** [enviroCar/enviroCar-app#202]
To extend enviroCar in the direction of a full blown sensor web we should start gathering sensor metadata. The list below is agnostic of whether it can be automatically collected or might require user interaction, and also ignores privacy issues.
- name and vendor of location sensor (http://developer.android.com/reference/android/hardware/Sensor.html)
- vendor / model of devices (adapter and phone)
- type of in-car sensors (captured outside of app, not automatically)

**Comment by SebaDro** [comment]
Due to inactivity, I will close this issue. Feel free to open it again, if still relevant.
