### ISSUE TITLE
DriveDeck creates strange measurements

### ISSUE THREAD

**Issue by matthesrieke** [enviroCar/enviroCar-app#211]
Two tracks, same car, just switched the adapters.

DriveDeck:
https://envirocar.org/api/stable/tracks/527a897ee4b08cecc59420d6

OBDII:
https://envirocar.org/api/stable/tracks/527a897ee4b08cecc5942145

DriveDeck receives negative `intake temperature` values.

the log for both tracks:
https://raw.github.com/matthesrieke/pasted-bins/master/dd_strange_measurements.txt

**Comment by dewall** [comment]
has been fixed some time ago
