### ISSUE TITLE
App stores two measurements for the same Time/Location

### ISSUE THREAD

**Issue by matthesrieke** [enviroCar/enviroCar-app#214]
E.g. see https://envirocar.org/api/stable/tracks/52b19f7ce4b0f9afbd14d773

The first measurement only has phenomena for GPS parameters, the second has both GPS and OBD parameters.

**Comment by matthesrieke** [comment]
gains new priority. this is still inside the app. needs quick action

**Comment by matthesrieke** [comment]
this is probably a result of ghost collector listening to the EventBus (thus the location updates). it might not be removed when the OBD connection closes.

**Comment by matthesrieke** [comment]
is this fixed via the workaround (I recall that...) or in a stable/reliable manner @dewall

**Comment by dewall** [comment]
yes, dirty but works. We should rework it when reworking the obd layer

**Comment by matthesrieke** [comment]
k, I keep it open for the release MS - so we won't forget ;)
