### ISSUE TITLE
Advanced algorithm for measurement point calculation

### ISSUE THREAD

**Issue by nuest** [enviroCar/enviroCar-app#220]
Currently there is a mismatch between the sampling rate of the sensor and the observation stored in the track (one point every two seconds).

The app should apply an algorithm to capture the 2,5 seconds before and after each measurement (the point that is actually stored) by calculating averages over all available values during that time interval. The SPF (https://wiki.52north.org/bin/view/SensorWeb/SensorPlatformFramework) contains such functionality and can also cover several variables (with different sampling rates etc.).

This is a quick sketch of a discussion between @matthesrieke and me on the topic:

![2014-02-21 09 51 20](https://f.cloud.github.com/assets/1325054/2228822/23651780-9ae2-11e3-8585-76acce16e17e.jpg)

This process could be described in SensorML.

**Comment by matthesrieke** [comment]
first prototype implemented. its now being tested with the new obd service layer

**Comment by dewall** [comment]
has been tested and integrated
