### ISSUE TITLE
LocationUpdateListener does not receive updates after certain situations

### ISSUE THREAD

**Issue by matthesrieke** [enviroCar/enviroCar-app#231]
E.g. a phone call was received and rejected while recording a track. after that, the app could not be re-opened (black screen; app crahses - see #230).

Also, LocationUpdateListener stopped receiving updates, but the UI of the phone indicated that GPS was still active. OBD connection remained open and pulled data succesfully.

Possible fix: do not use LocationUpdateListener - implement a Location listener in the Background Service implementation.

**Comment by dewall** [comment]
fixed!
