### ISSUE TITLE
Implement Profile Page

### ISSUE THREAD

**Issue by matthesrieke** [enviroCar/enviroCar-app#241]
Tasks needed to be done:
- avatar image download
  - an offline cache once the image was loaded (profile is available offline as well)
  - see concept of `RemoteDAO` and `CacheDAO` for examples on how other resources implement these
- time series graph
  - every track provides a statistics resource which contains min, max, avg for all available phenomena (e.g. https://envirocar.org/api/stable/tracks/53cc16eae4b04a9bce9c62ea/statistics)
  - implement the time series retrieval via a method `RemoteTrackDAO#getStatisticsForLatestUserTracks(int trackCount)`
  - focus on Consumption, CO2, Speed
- (anything else to add)

**Comment by dewall** [comment]
has been revised in principle
