### ISSUE TITLE
App Theming

### ISSUE THREAD

**Issue by matthesrieke** [enviroCar/enviroCar-app#243]
Hi Rahul,

since it looks like that creating a high contrast design is not as simple as we thought regarding to Johannes, I suggest to adjust scopes a bit here.

We discussed the ability to adjust themes for the app. The idea is to have the possibility to switch to a different theme with a simple adjustment of one parameter. There might be situations that we want to change the corporate design for a specialized target audience (e.g. a city-wide project, or for a company).

It would be great to have the ability to just "switch" the theme at compile time, not on the fly. So one distribution of the app cannot change its theme. I hope I am clear enough at this point :-)

We were wondering if there is already such thing available for android. A quick google search lead me to [this article](http://www.androidengineer.com/2010/06/using-themes-in-android-applications.html). I did not read through all of it, but I was missing the ability to adjust image resources (e.g. the logo) via that mechanism. Could you do some research and play around with this, once you have the other features at a mature level?

@nuest feel free to add anything I might have missed.

**Comment by dewall** [comment]
UI has already been revised
