### ISSUE TITLE
Simultaneous upload causes track duplicates on server

### ISSUE THREAD

**Issue by matthesrieke** [enviroCar/enviroCar-app#244]
The user can hit the "upload all" button and after that upload a single track via a long-click. This serializes the same track twice resulting in a duplication on the server side (as there are no duplication checks).

Implement a mutex (maybe using the UploadManager) and block uploading interaction as long as an upload takes place.

**Comment by matthesrieke** [comment]
is this still possible in the current UI? @dewall

**Comment by dewall** [comment]
good question...

**Comment by dewall** [comment]
The app has been revised and, as far as we know, this problem is no longer occured.
