### ISSUE TITLE
New Dashboard

### ISSUE THREAD

**Issue by rahulrj** [enviroCar/enviroCar-app#247]
1.I have introduced some new parameters on the dashboard. It shows speed,engine load  and co2 emission indicator for the diesel based vehicles while for the gasoline cars, fuel consumption,engine load and co2 emission indicators are displayed
1. Also each parameter has  a help icon besides it which shows the relevant information regrading that
   parameter like
   
   i> what does that parameter indicate?
   ii> what is the safe range for that parameter?
   iii> What happens if the value goes beyond the safe range?

**Comment by dewall** [comment]
a new dashboard has already been integrated.
