### ISSUE TITLE
Update license header

### ISSUE THREAD

**Issue by matthesrieke** [enviroCar/enviroCar-app#264]
This is the new license header that should be used:

```
Copyright (C) 2013 - 2015 the enviroCar community

This file is part of the enviroCar app.

The enviroCar app is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

The enviroCar app is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details.

You should have received a copy of the GNU General Public License along
with the enviroCar app. If not, see http://www.gnu.org/licenses/.

```

**Comment by matthesrieke** [comment]
@dewall can you provide a list of 3rd party libs+license? just for the sake of completeness..

**Comment by dewall** [comment]
com.squareup.dagger				dagger				1.2.2			Apache 2.0
com.jakewharton					butterknife			6.1.0			Apache 2.0
com.squareup					otto				1.3.8			Apache 2.0

com.squareup.retrofit 			retrofit			2.0.0-beta2		Apache 2.0
com.squareup.retrofit			converter-gson		2.0.0-beta2		Apache 2.0
com.squareup.retrofit 			retrofit-adapters	2.0.0-beta2		Apache 2.0
com.squareup.retrofit			adapter-rxjava		2.0.0-beta2		Apache 2.0

io.reactivex					rxjava				1.0.14			Apache 2.0
io.reactivex					rxandroid			1.0.1			Apache 2.0
com.jakewharton.rxbinding		rxbinding			0.2.0			Apache 2.0
com.f2prateek.rx.preferences 	rx-preferences		1.0.0			Apache 2.0
com.squareup.sqlbrite			sqlbrite			0.4.1			Apache 2.0

org.apache.commons				commons-compress	1.5				Apache 2.0
com.google.code.gson			gson				2.3				Apache 2.0
com.google.guava				guava				18.0			Apache 2.0
ch.acra							acra				4.6.2			Apache 2.0

com.afollestad					material-dialogs	0.7.6.0			MIT
com.github.lecho				hellocharts-library	1.5.5@aar		Apache 2.0
com.github.jorgecastilloprz		fabprogresscircle	1.01@aar		Apache 2.0
com.mapbox.mapboxsdk			mapbox-android-sdk	0.7.4@aar		Apache 2.0

**Comment by matthesrieke** [comment]
thanks, created a NOTICE https://github.com/enviroCar/enviroCar-app/blob/master/NOTICE

**Comment by dewall** [comment]
done!
