### ISSUE TITLE
GPS location problems

### ISSUE THREAD

**Issue by matthesrieke** [enviroCar/enviroCar-app#269]
The OBD connection was established, but the LocationHandler did not start locating. See attached log file.

The `LocationHandler` stops at `2015-11-16T19:26:28.048`. Still, the user triggered a `SERVICE_STARTED` at
`2015-11-16T19:26:28.727` and the OBD connection creates data. Eventually it stops as the GPS is not available...
[cleanup-gps-issue.txt](https://github.com/enviroCar/enviroCar-app/files/36388/cleanup-gps-issue.txt)

**Comment by dewall** [comment]
seems to be fixed ;)
