### ISSUE TITLE
IllegalStateException: "Already added!"

### ISSUE THREAD

**Issue by matthesrieke** [enviroCar/enviroCar-app#272]
app crash, see log: [alreay-added.txt](https://github.com/enviroCar/enviroCar-app/files/43079/alreay-added.txt)

[this](http://stackoverflow.com/questions/19441932/java-lang-illegalstateexception-fragment-already-added?answertab=votes#tab-top) might solve it?

**Comment by dewall** [comment]
I'm not 100% sure, but I think that this has been fixed!
