### ISSUE TITLE
NullPointerException in onStart() of BaseInjectorActivity

### ISSUE THREAD

**Issue by matthesrieke** [enviroCar/enviroCar-app#277]
very confusing, I do not know why this happens... somehow the (at some point) injected `mBus` gets null, resulting in the NPE. see attached log (timestamp: 2015-12-14T10:09:09.990).

[npe-base-injector.txt](https://github.com/enviroCar/enviroCar-app/files/60991/npe-base-injector.txt)

**Comment by matthesrieke** [comment]
maybe related NPE, in `onCreate()` of `BaseMainActivity` (timestamp: 2015-12-11T16:34:17.744). NPE happens when calling `mNavigationView.getMenu().findItem(R.id.menu_nav_drawer_tracklist_new);` - either `mNavigationView` or `.getMenu()` are null.

[npe-base-main.txt](https://github.com/enviroCar/enviroCar-app/files/60997/npe-base-main.txt)

**Comment by dewall** [comment]
has been fixed I guess :O
