### ISSUE TITLE
Snackbar is covering FAB 

### ISSUE THREAD

**Issue by csk1827** [enviroCar/enviroCar-app#311]
Snackbar is covering FAB like : 
![screenshot_2018-03-02-17-44-29](https://user-images.githubusercontent.com/18217329/36899000-382dc3e0-1e43-11e8-982a-29d5b87889a5.png)

In the following Activities : 
1. CarSelectionActivity
2. LogBookActivity

It can be solved by using CoordinateLayout in place of RelativeLayout which is used in the app.

**Comment by asaikarthikeya** [comment]
Merged ! Issue resolved.
