### ISSUE TITLE
Have to change colorPrimaryDark as per Material Guidelines

### ISSUE THREAD

**Issue by csk1827** [enviroCar/enviroCar-app#314]
In the app colorPrimary is dark blue(#0065A0) and colorPrimaryDark(#8CBF3F) is dark green which does not follow material design guidelines. As per google's guidelines colorPrimaryDark should be a darker variant of colorPrimary mentioned [here ](https://developer.android.com/guide/topics/ui/look-and-feel/themes.html)as : 

    
    <color name="colorPrimaryDark">#303F9F</color>

    
    <color name="colorAccent">#FF4081</color>

Current screen : 
![screenshot_20180302-234139](https://user-images.githubusercontent.com/18217329/36914586-d7c1b3a0-1e73-11e8-9350-387013e6165a.png)

After changing to a random darker variant of current primary color : 
![screenshot_20180302-234400](https://user-images.githubusercontent.com/18217329/36914611-e92ba0b0-1e73-11e8-9add-cbdaba21c8ac.png)

@dewall  please look into this issue and suggest an alternate primary dark color.

**Comment by dewall** [comment]
@SaiKrishna1827 I also tried to follow the design guidelines where possible. However, I was restricted by our crappy design guidelines found [here](https://github.com/enviroCar/enviroCar-marketing/tree/master/design_guideline). During the time of this coding, I had to equally bring green and blue into the style of the app. And there are 4 colors that does not fit together very well ;) But you are right, it looks smoother and not so aggressive.

I'm not 100% sure anymore, are there any other kind of influences on other parts of the app? If not, I'm with you and we could change it.

**Comment by SaiKrishna1827** [comment]
@dewall I think there will not be any negative implications anywhere in the app by changing the primary dark color. Wherever green color is necessary, "green_dark_cario" is used explicitly(Line color of the graph in TrackStatistics Activity, Start Button in Dashboard Fragment etc.) Rather we will have a good look and feel if we change the color.

**Comment by dewall** [comment]
has been solved in the meantime. Closing this issue
