### ISSUE TITLE
Show only the email clients in Report Issue Fragment

### ISSUE THREAD

**Issue by csk1827** [enviroCar/enviroCar-app#317]
Instead of showing only the email clients, the Report Issue Fragment is showing multiple unsupported clients (WhatsApp, Bluetooth etc.). 

![device-2018-03-03-010329](https://user-images.githubusercontent.com/18217329/36918260-54990c24-1e7f-11e8-987a-b0b9f83efbd5.png)

**We need to only display the clients which can send Emails.**

**Comment by asaikarthikeya** [comment]
The app UI has been revised in the recent years. Now the app only shows email clients while sending a report. 

![Screenshot_20210724-123205_Android System](https://user-images.githubusercontent.com/70392921/126860502-6c31ca23-7c82-4889-add2-ad62a94f18ba.jpg)

Please feel free to reopen this issue, if it still exists in your device. Thank you.
