### ISSUE TITLE
Viewing track in Map is not comfortable, when user opens a specific track details.

### ISSUE THREAD

**Issue by csk1827** [enviroCar/enviroCar-app#322]
When the user opens specific track details, we can see a MapView which contains the track path in collapsing toolbar layout. The user cannot view the track path(as shown below) in the map view comfortably. 

![svid_20180401_101840 1](https://user-images.githubusercontent.com/18217329/38170059-19ebd6fc-3599-11e8-8cea-9eaf5df2ea80.gif)

It should be like the following screenshot taken from Google Fit app so that the user can comfortably view the track path.

![svid_20180401_101859 1](https://user-images.githubusercontent.com/18217329/38170069-6dd3c07c-3599-11e8-8842-e1af73a2fef2.gif)

**I want to work upon this issue.**

**Comment by asaikarthikeya** [comment]
Merged ! Issue resolved.
