### ISSUE TITLE
Update the libraries used to the latest versions

### ISSUE THREAD

**Issue by csk1827** [enviroCar/enviroCar-app#324]
As the development of this repository paused in 2016, many libraries used in the repository which are then new are now old. So it is better to update the libraries to the latest versions. The following library updates are worth mentioning.

- Dagger 1 to Dagger 2
- Gradle version and Android Gradle Plugin version
- Build tools version and Android Support Libraries version
- Butterknife Library version

**Comment by asaikarthikeya** [comment]
Merged ! Issue resolved. #743
