### ISSUE TITLE
Map image not loading on some devices due server timeout error. Need place holder in case of failure.

### ISSUE THREAD

**Issue by Hashik-Donthineni** [enviroCar/enviroCar-app#329]
**Description**: The map on my phone with stock OS and Android 9.0 (Moto X4) failed to load the map (please refer the images) a point to note is that it works fine in Emulator with the same OS, I run a 40mb/s Internet. A possible reason for not loading might be the issue of OpenStreetMap API.

**STR**: Just sign-in and go to My Tracks > Uploaded Tracks **works on only some devices as mentioned above**

**Possible solution**: ~~Having a proper way of showing a place holder in place of a failed map image. The place holder code can be placed in GPSOnlyConnectionService > at catch block logging statement.~~

Error log: 
![Error Log](https://user-images.githubusercontent.com/22850179/53574878-7d031d00-3b96-11e9-8ffc-3e1029848807.png)
`2019-02-28 19:51:17.611 1621-1926/org.envirocar.app E/WebSourceTileLayer: Error downloading MapTile: http://tile.openstreetmap.org/2/2/0.png:java.net.SocketTimeoutException: failed to connect to tile.openstreetmap.org/140.110.240.7 (port 80) from /25.104.154.248 (port 39259) after 10000ms`

![SS1-MapImageLoadingFailed](https://user-images.githubusercontent.com/22850179/53574459-b0917780-3b95-11e9-93d7-81757688df62.png)
After sometime: 
![SS2-MapImageLoadingFailed](https://user-images.githubusercontent.com/22850179/53574468-b424fe80-3b95-11e9-98f7-1656d5ab87e6.png)

**Comment by dewall** [comment]
Unfortunately, I cannot reproduce these issues (tested on Android 6 and 9) and I've never experienced this before. The visualization bug in the second picture is strange since it does not correspond to the normal layout of maptiles. However, the library used for the MapView is quite outdated and should be replaced in the future….

**Comment by Hashik-Donthineni** [comment]
In that case, I think we can consider this under issue #324 I tried upgrading the mapboxsdk from 0.7.4 to 7.1.2 but ran into some errors, I'll post the updates after I am done. Please close the issue as we can further refer #324 instead.
