### ISSUE TITLE
Buggy MapView nested within ScrollView

### ISSUE THREAD

**Issue by 0xamogh** [enviroCar/enviroCar-app#331]
Cause: ScrollView for a dynamic element like a zoom-able map, the device cannot differentiate between the strokes that are intended for zooming the map and those intended for going down the scroll list. This leads to a buggy behavior which I have attached a video of here.
![videotogif_2019 03 15_21 13 53](https://user-images.githubusercontent.com/31567169/54512800-5eb16580-497b-11e9-9619-2cf73f30a077.gif)

 I am working on fixing the issue.

**Comment by asaikarthikeya** [comment]
The app UI has been revised. Now Mapview is displayed in full screen. Therefore, I am closing this issue for now.


https://user-images.githubusercontent.com/70392921/126860761-0ca8468b-1ead-4302-9ac9-235809a6b5c2.mp4
