### ISSUE TITLE
App crashing when clicked on the card in local tracks

### ISSUE THREAD

**Issue by Hashik-Donthineni** [enviroCar/enviroCar-app#333]
When we start a track and goto local tracks, the track is shown there and if there are no measurements the exception is called while loading the track and crashes on click.
Reference Gif: App crashes at the end.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22850179/54806020-ce3a9400-4c9e-11e9-9fd1-000342d1aa17.gif)
: (App crashe)

**Comment by asaikarthikeya** [comment]
The app UI has been changed in the recent years. Now this issue doesnot exists. Feel free to reopen if you still face this issue. Thank you.
