### ISSUE TITLE
[Typo] "Licensen" to "Lizenz" on "Andere Einstellungen" screen

### ISSUE THREAD

**Issue by EHJ-52n** [enviroCar/enviroCar-app#361]
![Screenshot_20191015-162616](https://user-images.githubusercontent.com/3839896/66841129-80061e80-ef69-11e9-9527-22d7687473ed.png)

**Comment by SebaDro** [comment]
The app UI has been updated in the meanwhile, so that the "Other Settings" view is no more existent. Therefore, I will close this issue. Feel free to open it again, if you have any doubts.
