### ISSUE TITLE
Update link to envirocar homepage: http -> https

### ISSUE THREAD

**Issue by EHJ-52n** [enviroCar/enviroCar-app#362]
![Screenshot_20191015-162616](https://user-images.githubusercontent.com/3839896/66841179-94e2b200-ef69-11e9-8600-52457ad9cc78.png)

**Comment by asaikarthikeya** [comment]
The app UI has been updated. New app UI doesnot contain this issue. Therefore, I will close this issue. Feel free to open it again. Thank you.
