### ISSUE TITLE
[Typo] on "Optionale Einstellungen" screen 

### ISSUE THREAD

**Issue by EHJ-52n** [enviroCar/enviroCar-app#363]
![Screenshot_20191015-162709](https://user-images.githubusercontent.com/3839896/66841269-bb085200-ef69-11e9-9b67-ed78a1ceb95d.png)

Optionale [Funktionen]
[Mess-Häufigkeit/Frequenz]
Das Zeit-Delta zwischen zwei M[e]ssungen...
...nur dann, wenn Sie s[i]ch auch der Konsequenzen bewusst sind.

Beta [Funktionen]
...befindet sich im Beta[-]Stadium...

https://de.wikipedia.org/wiki/Leerzeichen_in_Komposita

**Comment by asaikarthikeya** [comment]
Merged into the master branch!
