### ISSUE TITLE
Start Screen message - don't use the app while driving!

### ISSUE THREAD

**Issue by AlbertRemke** [enviroCar/enviroCar-app#366]
The start screen should alert the user that the app must not be operated while driving, just for traffic safety..

**Comment by Hemant27031999** [comment]
Is anyone working on this issue ?

**Comment by Hemant27031999** [comment]
@AlbertRemke , please let me if this feature is still needed in the app?

**Comment by dewall** [comment]
Hi Hermant, unfortunately, this feature has already been partly realized but not yet committed. We exepct to push the finalized changes in the upcoming weeks.

**Comment by Hemant27031999** [comment]
Ok. Thanks @dewall for replying.

**Comment by sanchi0204** [comment]
Is this issue available to work?

**Comment by SebaDro** [comment]
This feature has been introduced as part of #835. The start screen now shows a warning message as depicted below:

<img src="https://user-images.githubusercontent.com/18207870/136158025-e3185551-7eeb-4cb8-9805-a6861004cfa7.jpg" width="400">

@AlbertRemke: Does it fullfill you expectations for such a warning? If so, I will close this issue.

**Comment by asaikarthikeya** [comment]
Merged into the master branch! If this doesnot meet the expectations, do consider reopening the issue @AlbertRemke
