### ISSUE TITLE
Time series of measurements - two very similar parameters

### ISSUE THREAD

**Issue by AlbertRemke** [enviroCar/enviroCar-app#369]
Track statistics -> time series diagrams -> menue for selecting the parameter to be displayed: 
The menue offers two very similar parameters "Geschätzter Verbrauch" and "Geschätzter Energieverbrauch". It should be clarified: what is the difference/why these two parameters..

**Comment by SebaDro** [comment]
With commit https://github.com/enviroCar/enviroCar-app/commit/1ce17f108898d02909afb1a7c1fad32b21afff53 one of the parameters has been already renamed to indicate that it has been calculated from GPS based mesurements. This should do it.
