### ISSUE TITLE
App crash on export track

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#389]
**Describe the bug**
App crashes on Export track .

**To Reproduce**
1. Goto My Tracks Fragment
2.  Select the menu of the track to be exported.
3. Select export track.

**Why app is crashing**
getUser() is null 

**How i will fix**
Check if user logged in or not in case not logged in show snackbar showing message login to export

**Comment by asaikarthikeya** [comment]
Merged ! We can close this issue now @arvindnegi1. Thank you.
