### ISSUE TITLE
Add option to share app in settings screen

### ISSUE THREAD

**Issue by neel1998** [enviroCar/enviroCar-app#393]
Adding option of share app will allow users of this app to share it easily with others..

**Comment by arvindnegi1** [comment]
@neel1998 are you working on this?

**Comment by asaikarthikeya** [comment]
Working on this.

**Comment by arvindnegi1** [comment]
> Working on this.

#430

**Comment by asaikarthikeya** [comment]
> > Working on this.
> 
> #430

Thankyou

**Comment by pree-T** [comment]
is this issue still open? May I work on this?
