### ISSUE TITLE
Using Material Views to change the design of Login and SignUp screen

### ISSUE THREAD

**Issue by VibhorChinda** [enviroCar/enviroCar-app#398]
![WhatsApp Image 2020-02-05 at 3 08 26 PM (1)](https://user-images.githubusercontent.com/46090233/73829916-c4277280-4829-11ea-8604-bdafbf5395ae.jpeg)
![WhatsApp Image 2020-02-05 at 3 08 26 PM](https://user-images.githubusercontent.com/46090233/73829980-e3260480-4829-11ea-80df-59b812936ec2.jpeg)

**Comment by VibhorChinda** [comment]
@dewall sir i guess we can change old edit text fields to new material designed text fields to change the look and feel of the login and signup activities.

Would like to hear what you think on this.

**Comment by dewall** [comment]
hi @VibhorChinda, it depends what you want to realize. If it feels like an upgrade, you are invited to make a suggestion.

**Comment by VibhorChinda** [comment]
so @dewall sir what do you suggest should i go forward with this upgradation ?
Like i would suggest using the material design views would be nice in terms of providing good user interface.

**Comment by csk1827** [comment]
@VibhorChinda if you want to completely change the layout, please provide a mock design by using some designing softwares online/offline. If you just want to change the old edit text fields, then go ahead, do it, and post it here, if you feel that as a good upgrade.

**Comment by VibhorChinda** [comment]
ok @VibhorChinda sir i will go ahead with the with the upgrade.
