### ISSUE TITLE
Password security check

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#399]
**Describe the bug**
Register with weak password possible .

No check for weak password.

**How i will fix**
Before registering i will check if the password is strong or not comparing on the basis of regular expression pattern.

**Comment by arvindnegi1** [comment]
@dewall sir, i would like to work on this if it is relevant doing so.

**Comment by dewall** [comment]
@arvindnegi1 seems like you already worked on that issue ;) I will review the changes tomorrow (hopefully)
