### ISSUE TITLE
Allow swipe between fragments

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#401]
**Describe the bug**
This is not bug rather this is enhancement .
Add feature to change fragment on swipe left or right.

**To Reproduce**
1. Launch app.
2. Swipe left or right between fragments.
3.  Nothing happens.

**My approach of doing this**
Using ViewPager to swipe between fragments.

**Comment by arvindnegi1** [comment]
@dewall sir, is this fine doing so?

**Comment by dewall** [comment]
@arvindnegi1 looks good. In the beginning, I had doubts whether the "nested swipes" would work out of the box.
