### ISSUE TITLE
Adding OnBoarding screens for the application

### ISSUE THREAD

**Issue by VibhorChinda** [enviroCar/enviroCar-app#402]
This could be a great enhancement for the application.
As nowadays each and every application that is being used carry a splash screen followed by an OnBoarding screen.

The OnBoarding screen can provide a great uses experience to the users of the application providing them information about the app with some great visuals.

@dewall would love to hear your point on this sir ?

**Comment by dewall** [comment]
I agree that an Onboarding screen is valueable for the app and we already thought about the integration. However, it requires to think carefully about the integration and the content it needs to show. In addition, it requires some good looking and explaining pictures. This makes this task being very time consuming where I cannot give much assistance. If you want to invest the time, then you are invited to do so.

**Comment by VibhorChinda** [comment]
Thank you for feedbacks @dewall sir

**Comment by asaikarthikeya** [comment]
Thank you for your suggestion @VibhorChinda. This is done as a part of GSoC 2020 in the issue #541. PR is made and is approved by dewall sir.
