### ISSUE TITLE
Set ime option to edit text in login activity

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#407]
**Describe the bug**
Click on keyboard enter or next button it is expanding the edit text rather then pointing directly to next edit text.

**To Reproduce**
1.Open login activity.
2.  enter user name.
3. click on keyboard next button.
Not pointing to next edit text rather it expanding the edit text of username.
<table>
<th>Gif of the current behaviour</th>
<tr>
<td><img src="https://user-images.githubusercontent.com/33172321/74023766-6b411100-49c6-11ea-9916-5452db8572fb.gif" height="500" width ="400">
</td>
</tr>
</table>

**Why we need this**
For better user experience click on next in keyboard should point to next edit text.

**Comment by arvindnegi1** [comment]
@dewall sir, cai i work on this?

**Comment by csk1827** [comment]
It is a valid issue. You can start working on this.

**Comment by VibhorChinda** [comment]
@csk1827 sir and @arvindnegi1 sir i think the issue (https://github.com/enviroCar/enviroCar-app/issues/398) would handle this issue too.

**Comment by arvindnegi1** [comment]
@VibhorChinda sir, you must be replacing EditText with com.google.android.material.textfield.TextInputEditText but that will not solve this issue ;)

**Comment by VibhorChinda** [comment]
@arvindnegi1 sir, if i would change the text fields i would enable their the toggle option as well as the single line input option which i guess would solve this issue and also in addition would provide the toggle option to us.

**Comment by arvindnegi1** [comment]
@VibhorChinda sir, but that will not handle implicit submit after click on go in password edit text field for sure. We have to check for ime action in SignInActivity.java .

**Comment by VibhorChinda** [comment]
@arvindnegi1 sir, I guess what you were pointing out in this issue was the problem of text fields expanding rather than moving to next text field.

I guess you should make a new issue describing how to handle the implicit action.
Don't take me wrong but is it necessary for implementing the implicit action when there is a login button.

**Comment by arvindnegi1** [comment]
@VibhorChinda sir, i clearly mentioned in "Set ime option to edit text in login activity" means i am also setting ime action to edit text password so it is very much clear setting ime action to password edit text should perform the submit for that we have to add some code in .java. Thank you ;).
