### ISSUE TITLE
Sub Optimal splash screen implementation 

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#412]
## Description of Bug
Currently on first time launching app (cold startup) their is lag for starting splash screen activity (see below gif attached ) and i found that in splash screen activity it has been hardcoded time value to 2 second.
**need of splash screen in optimal way**
The splash screen is for giving visual feedback for the user while they are waiting for app to load. Currently it has been hardcoded to 2 second which is bad as if user has powerful mobile they have to wait even if phone able to launch it in fraction of second. Also for the user having low-end device has to wait even longer.

<table>
<tr>
<th>See lag for starting splash screen</th>
</tr>
<tr><td><img src="https://user-images.githubusercontent.com/33172321/74084152-284c6f80-4a92-11ea-9fac-4eec98c019dd.gif" height="500"></img>
</td>
</tr>
</table>

- Lag is because app is loading to launch 
- also after the app has loaded the splash screen is hardcoded with 2 sec

## Expected behaviour
While app is loading we have to show the UI and it should not be hardcoded with any time. It should depend on phone how much time it will take to load.

## How will i solve this issue
Set window background in splash screen activity theme and remove all the hardcoded time in SplashScreenActivity only contain startactivity(reference to other activity).

**Comment by arvindnegi1** [comment]
@dewall sir, i would like to work on this if you feel this right doing so.
Also sir for this i have to make drawable xml of the splash screen(means i have to design the splash screen in photoshop and set it in drawable xml)   layout to set in windowBackground.
splash screen layout will be removed.
Sir i am not sure it is right or wrong to do so. Waiting for your point of view on this so that i can start working.

**Comment by dewall** [comment]
@arvindnegi1 the 2 seconds are rather intentional than a bug. But I agree that 2 seconds can be reduced to a second. In addition, designing the splash screen in photoshop reduces the flexibility of that approach. We also intend to add some other kind of information on this page such as the "Don't use while driving" hint.

**Comment by arvindnegi1** [comment]
@dewall sir, thank you for your reply. I agree with your opinion.

**Comment by asaikarthikeya** [comment]
@arvindnegi1 Can we close this issue?
