### ISSUE TITLE
Reactive edit text field in Signup

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#414]
## Describe the bug
Currently the validity of email password check when we click submit button.

## Why we need this
It will be  better if on input text in edit text it should validate at the same time while typing in so that every time user donot have to submit and check what user has done wrong in input.

**Comment by arvindnegi1** [comment]
@dewall sir, i think its good enhancement in user point of view. 
looking forward to your decision on this so that i can start working.

**Comment by dewall** [comment]
@arvindnegi1 It's a valid point
