### ISSUE TITLE
No bluetooth rescan option in OBD-II Adapter selection

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#418]
## Description of issue
No option for re discover the bluetooth device in range.
## To Reproduce
Steps to Reproduce 
1. Select dashboard fragment.
2. Select OBD-II adapter.
Open up OBD-II Adapter Selection
- It only scan once when it is opened.
- User has no option to rescan for nearby bluetooth device(OBD-II in this case) .

**Comment by arvindnegi1** [comment]
@dewall sir, i would like to work on this.

**Comment by dewall** [comment]
@arvindnegi1 valid point
