### ISSUE TITLE
Drop down menu enhancement

### ISSUE THREAD

**Issue by Sarthak2601** [enviroCar/enviroCar-app#428]
**Description of Issue-**
The drop down menus(both logged out and logged states) have just one option, so replacing that drop-down menu with an icon menu might enhance UX. 
 
**Solution**
- Add the required drawables. 
- Set up those drawables in menus as icons and set showAsAction.

**Would you like to work on this ?** Yes.

**Comment by Bhavya-22** [comment]
Pr for this is created 
#686 
@arvindnegi1 Sir please review it and let me know if any changes is required
