### ISSUE TITLE
Dublicate upload of tracks

### ISSUE THREAD

**Issue by dewall** [enviroCar/enviroCar-app#437]
There is currently an issue where tracks get uploaded twice when automatic upload is activated.

**Comment by arvindnegi1** [comment]
@dewall sir, can I work on this if you give me permission?

**Comment by dewall** [comment]
sure

**Comment by arvindnegi1** [comment]
@dewall sir, i tried to reproduce the issue. Sir, on tack my fragment uploaded view it does not show duplicate data.

**Comment by asaikarthikeya** [comment]
@dewall Hello Sir, I have tested this multiple devices, I havenot seen such behaviour of duplicate data. So, I am closing this issue. Feel free to reopen if you this issue still persists in your device. Thank you ;-)
