### ISSUE TITLE
Link in help page is not working

### ISSUE THREAD

**Issue by neel1998** [enviroCar/enviroCar-app#446]
Link to enviroCar.org is not working in help page
![20200221_021519](https://user-images.githubusercontent.com/32041242/74977194-43cf5700-5450-11ea-8e74-82dd28802757.gif)

**I would like to work on this issue**

**Comment by arvindnegi1** [comment]
already fixed #410 .
I hope you are using the updated code base.

**Comment by neel1998** [comment]
Oh okay. May be i am testing with older apk
