### ISSUE TITLE
Privacy statement pop up appearing everytime app is opened

### ISSUE THREAD

**Issue by neel1998** [enviroCar/enviroCar-app#449]
The privacy statement pop up should not appear once it has been accepted. Showing it every time user opens the app is irritating.
![20200221_023228](https://user-images.githubusercontent.com/32041242/74978489-b6413680-5452-11ea-9f10-e76aef83a048.gif)

**I would like to work on this issue**

**Comment by anonghostteamz** [comment]
I don't know why but I don't face this issue on my phone.

**Comment by asaikarthikeya** [comment]
Unable to reproduce this issue.

**Comment by SebaDro** [comment]
It's likely, that this issue has already been fixed in the meantime. Feel free top open it again, if it's still present.
