### ISSUE TITLE
Use dagger android dependencies

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#450]
## Description 
Currently we are using dagger 2 but we can use dagger android so we do not have to every time do void Inject().

**Comment by arvindnegi1** [comment]
@dewall sir, i would like to work on this, if this is right doing so. Thank you

**Comment by asaikarthikeya** [comment]
@arvindnegi1 I am not very good with dagger, but on the little search I found that  void Inject() is used in dagger 1 and dagger 2 is a updated version. And dagger 1 is deprecated. Should this be worked on?

**Comment by arvindnegi1** [comment]
I didn't get any confirmation about this from previous mentor. Closing this!
