### ISSUE TITLE
Add a feature to upload locally stored tracks in the app

### ISSUE THREAD

**Issue by neel1998** [enviroCar/enviroCar-app#455]
Currently in the my tracks section we can only see the tracks that have been recorded by our device. However, this restricts users from sharing their track data with other peers.

This feature allows users to upload a previously tracked data into the app. So now I can export my track, send it to my friend and then my friend can easily open my track in his app.

**I would like to work on this issue**

**Comment by arvindnegi1** [comment]
@neel1998  this has been already discussed in #397
