### ISSUE TITLE
Hide FAB in MyTracks (Local) on scroll

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#458]
## Description
Hide FAB on scroll in MyTracks Local tab.

<table>
<th>My Tracks local
</th>
<tr>
<td><img src="https://user-images.githubusercontent.com/33172321/75029273-c34c3d00-54c7-11ea-8366-d78d8c612e06.png" height=500 >
</td>
</tr>
</table>

**Why we need this**
For better user experience.

**How will I implement**
Hide the Fab when user scroll up or down in scroll listener.

**Comment by arvindnegi1** [comment]
@dewall sir, i would like to work on this

**Comment by neel1998** [comment]
@arvindnegi1 when will you make the FAB re appear?

**Comment by arvindnegi1** [comment]
@neel1998  when user stop scrolling.

**Comment by neel1998** [comment]
Okay... I don't think this is very common feature. Like most of the widely used apps keep the FAB constant (eg whatsapp).

**Comment by arvindnegi1** [comment]
@neel1998 yes i agree with you , but the issue is FAB is hiding the text inside card view.
So i think we can show or hide FAB on scroll. It will hide if user scroll down and visible on slightly scroll up. Thanks.

**Comment by asaikarthikeya** [comment]
> @neel1998 yes i agree with you , but the issue is FAB is hiding the text inside card view.
> So i think we can show or hide FAB on scroll. It will hide if user scroll down and visible on slightly scroll up. Thanks.

FAB hiding the texts take place in other apps also. I feel it is better to keep the FAB constant as users are used to this behaviour across the other apps. Hence, I am closing this issue for now. Feel free to reopen. Thank you ;)
