### ISSUE TITLE
Add general profile settings in setting section

### ISSUE THREAD

**Issue by anonghostteamz** [enviroCar/enviroCar-app#462]
Add some general profile settings like changing the profile picture, update username and password.
It will help to enhance the app user interface.
**Can I work on this issue?**

**Comment by anonghostteamz** [comment]
I would like to work on this issue if I got permission.

**Comment by ojasjain24** [comment]
can I work on this?

**Comment by BolisettySujith** [comment]
Can I work on this???

**Comment by asaikarthikeya** [comment]
@anonghostteamz There are few other issues that also propose similar features. Which marks this as a duplicate issue. As of now these features cannot be implemented in the app-side as they have to be implemented in the server first. Thank you for suggesting these great features ;)
