### ISSUE TITLE
Improve loader layout

### ISSUE THREAD

**Issue by avikumar15** [enviroCar/enviroCar-app#467]
Currently, the loader has the text and progress bar left-aligned, which looks quite odd.

![oldloader](https://user-images.githubusercontent.com/41758822/75099778-819dbe00-55bd-11ea-9899-114157178e5f.png)

The loader will look much better if it is center aligned, something like this :

![newloaderlogin](https://user-images.githubusercontent.com/41758822/75099817-0c7eb880-55be-11ea-80e2-35df164b2e62.png)

Yes, I would like to work on this issue.

**Comment by asaikarthikeya** [comment]
Implemented in #747 .

**Comment by SebaDro** [comment]
I will let this issue open until #747 is merged back to the master branch.

**Comment by asaikarthikeya** [comment]
Merged into the master branch!
