### ISSUE TITLE
No option to stop uploaded track download

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#470]
## Describe the bug
Currently when user click on download icon in uploaded track it start downloading track but what if user want to stop download.
## What is expected
Download icon should change to cancel and  on click on cancel it should stop downloading track.

**Screenshoot attached**
<img src="https://user-images.githubusercontent.com/33172321/75112785-20352800-566d-11ea-88f5-826d9d4c3865.png" height=500></img>

**Comment by arvindnegi1** [comment]
@dewall sir, i want to work on this if you find it right doing so. Thank you :)

**Comment by dewall** [comment]
you can do so
