### ISSUE TITLE
Replace AsyncTask with RxJava in AbstractTrackListCardAdapter

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#472]
## Description
Currently AsyncTask is used but RxJava provide much flexibiity and better for processing results.

**Comment by arvindnegi1** [comment]
@dewall sir, i would like to work on this.

**Comment by asaikarthikeya** [comment]
I have spoke about this issue with Sebastian sir, He mentioned that this enhancement is not essential at this moment. Can we close this @arvindnegi1 ?

**Comment by asaikarthikeya** [comment]
Closing this issue :)
