### ISSUE TITLE
Redesign login/register views

### ISSUE THREAD

**Issue by yeltayev22** [enviroCar/enviroCar-app#474]
After discovering app I show that the ui for login/register page is a quite ugly and old. If your login or email is long enough, it is not shown fully. Also, there are many issues with ui features like overlapping `error icon` with `show password` icon, disappearing the map in the background when the keyboard is shown. Also, there is no `show password` icon in the login page. 

UPD: 
@dewall Can you look at this?
Everyone feel free to comment, if something needs to be changed.
For accepting Terms and Conditions I made two versions.
[DESIGN IS HERE](https://www.figma.com/file/2C3XkTxbyJULRoTlIL8RE6/EnviroCar-login-%2F-register?node-id=0%3A1)
![photo_2020-02-26_13-06-33](https://user-images.githubusercontent.com/26632163/75320439-e2b4e280-5898-11ea-86e5-362b95e8012e.jpg)
![photo_2020-02-26_13-06-39](https://user-images.githubusercontent.com/26632163/75320442-e47ea600-5898-11ea-9e6d-74cbd9c8949c.jpg)

**Comment by yeltayev22** [comment]
@dewall Can you look at that?
Everyone feel free to comment, if something needs to be changed
[DESIGN IS HERE](https://www.figma.com/file/2C3XkTxbyJULRoTlIL8RE6/EnviroCar-login-register?node-id=0%3A1)

**Comment by dewall** [comment]
@yeltayev22 Looks good but there is still room for improvement. You already worked on that?

**Comment by yeltayev22** [comment]
@dewall Not yet. I was waiting for comments. What needs to be improved?

**Comment by dewall** [comment]
I would make it a little bit more consistent with the other layouts such as making the blue color a first class citizen of that view (e.g. toolbar until "Create an account.." or something like that)

I don't know whether there are GDPR based regulations but we also need to split a single checkbox into two: one for the Terms and Conditions and one for the Privacy Policy. We don't target to make a dialog for accepting the terms. Instead we have to continue with the checkbox approach.

**Comment by dewall** [comment]
@yeltayev22 I currently have to investigate on this view. Any plans on how fast you are able to contribute? Otherweise, I maybe have to improve some aspects on my own.

**Comment by yeltayev22** [comment]
@dewall I also thought about making the toolbar blue, as in other places. What do you mean with fast contribution, is it about design or implementation?

**Comment by dewall** [comment]
I'm asking you whether you want to contribute and implement your views.

Depending on how fast you are able to realize that, I can integrate this into the app. If it takes some time, it is not possible for the next months since we have a project where something like a handbook has been created and very soon we cannot adjust the screenshots in this handbook anymore.

**Comment by yeltayev22** [comment]
@dewall Oh, I got it. How much time do I have? I think it will take about 1 - 1.5 weeks.

**Comment by dewall** [comment]
a few days =)

**Comment by yeltayev22** [comment]
what if I will add/implement this as my GSOC project idea? And how much do you mean by "a few days"? :)

**Comment by dewall** [comment]
github and gsoc are two different things. You posted it here and not as part of a gsoc proposal.

I guess monday the latest.

**Comment by yeltayev22** [comment]
Ok then. I guess to implement and test all the stuff needs some time. And trying to implement this fast because of deadline is a bad idea.
Sorry, I will try add this to GSOC then.

**Comment by sanchi0204** [comment]
Can I work on this issue?
