### ISSUE TITLE
Tracklist Fragment not refreshing on data change

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#475]
## Describe the bug
On data change and swipe between different fragment tracklist fragment data not updating to new dataset. It is updating on closing and relaunching app.
Also after finishing track recording local track list is not updating we have to relaunch the app for that. 
## To Reproduce
**case first**
1. Click on FAB to upload all local track.
Successful uploaded but no message pop up.
Fragment does not refresh  means if all local track uploaded successfully all track should move to 
uploaded and local track should not contain any track list. 

**case second**
1. Start track recording.
After finish track recording data in local track list not updating we have to relaunch app.

<table>

<th>Gif of the behaviour case first</th>
<tr>
<td><img src="https://user-images.githubusercontent.com/33172321/75356714-53c6bb00-58d6-11ea-98d0-b57149168d7f.gif" height=500>
</td>
</tr>
</table>

**i would like to work on this**

**Comment by arvindnegi1** [comment]
@dewall sir, i would like to work on this.

**Comment by dewall** [comment]
just do it

**Comment by SebaDro** [comment]
Fixed with 02aeb0bb and #820
