### ISSUE TITLE
Add the ripple effect to buttons

### ISSUE THREAD

**Issue by avikumar15** [enviroCar/enviroCar-app#476]
I see that some of the buttons having a background, don't any longer posses a ripple effect. However, I feel the ripple effect makes UI more immersive and better. Some buttons include - Login button, Register button, etc. So, having a ripple effect + background will be ideal.
Yes, I would like to work on this issue.

**Comment by asaikarthikeya** [comment]
With the current implementation, Adding a ripple effect doesnot match the UI of the app. Thanks for sharing your views :)
