### ISSUE TITLE
Change login and logout structure

### ISSUE THREAD

**Issue by avikumar15** [enviroCar/enviroCar-app#478]
When we start the app, the app takes us to the dashboard directly. I feel the app should ideally first launch the login activity where authentication will occur, and only after authentication is successful, the dashboard should open. Similarly, when the user logs out, the user should be directed to login activity, instead of a simple snackbar.
Yes, I will like to work on this issue.

**Comment by arvindnegi1** [comment]
@avikumar15 i think this is not needed because whether or not user is logged in user can record track. :)

**Comment by dewall** [comment]
agreed, not required because we don't want to force users to create an account.
