### ISSUE TITLE
Better UI using snackbar.

### ISSUE THREAD

**Issue by KaairaGupta** [enviroCar/enviroCar-app#484]
A `Toast` appears with the respective text at the following places, but it would better if we use `snackbar` in its place:
- Network error at login/register screen
- Logout -> "Goodbye, <username>."

If anyone else find any other similar issue, please comment in this thread.

Its a minor upgrade only, but can be a good first issue.

Being a beginner only, I am interested to work on this issue.

**Comment by arvindnegi1** [comment]
@KaairaGupta  it already shows snackbar not toast. :)

**Comment by KaairaGupta** [comment]
Is it updated in the `develop` branch? (I am new to this project and thus not well-informed.)

**Comment by arvindnegi1** [comment]
Yes it is
