### ISSUE TITLE
OBD-II Adapter Selection marks two items selected if they have same name.

### ISSUE THREAD

**Issue by KaairaGupta** [enviroCar/enviroCar-app#485]
Please look at the following screenshot:
![OBD-II Selection (2)](https://user-images.githubusercontent.com/45488611/75565347-c620d200-5a73-11ea-858b-7278b6250a5f.jpg)

You will notice that radio button is used to select the OBD-II adapter, but still two items from list are marked simultaneously. User does not have option to do so, but this automatically happens if two bluetooth devices have the same name.

The implementations needs a minor change that list item is marked according to the bluetooth device id, and not the name.

**I would like to work on this issue.**

**Comment by dewall** [comment]
I mean this is a bug and you can definitely start on that on your own

**Comment by arvindnegi1** [comment]
@KaairaGupta are you working on this? if not i would like to work on this.
