### ISSUE TITLE
[UI/BUG] Empty uploaded screen under "My Tracks"

### ISSUE THREAD

**Issue by avikumar15** [enviroCar/enviroCar-app#492]
When I open the app and select Uploaded Tracks under My Tracks, the screen shows the following at first (which is desired) :

![WhatsApp Image 2020-03-09 at 1 22 24 PM (1)](https://user-images.githubusercontent.com/41758822/76227369-20a9f300-6217-11ea-894d-e3f45e6064de.jpeg)

But the next time we open the same fragment without closing the app we get :

![WhatsApp Image 2020-03-09 at 1 22 24 PM](https://user-images.githubusercontent.com/41758822/76227468-42a37580-6217-11ea-9d78-c692d42075fb.jpeg)

I would like to work on this issue.

**Comment by arvindnegi1** [comment]
#454 duplicate .

**Comment by avikumar15** [comment]
> #454 duplicate .

It's not exactly duplicate, the issue is different. The current issue is about solving the existing "bug" that prevents from viewing the placeholder when we open the tracks fragment for the second time or later.

**Comment by asaikarthikeya** [comment]
@avikumar15 Closing this issue as this is a duplicate issue of #454. #454 also describes the same issue of placeholder not being displayed.
