### ISSUE TITLE
[MOD] Migrate ListView to RecyclerView

### ISSUE THREAD

**Issue by avikumar15** [enviroCar/enviroCar-app#502]
I see that a list view is used in LogBook Activity instead of the more preferred Recycler View. Recycler View will allow more flexibility and better UI options.
I would like to work on this issue if it feels right to you @dewall sir

**Comment by asaikarthikeya** [comment]
This enhancement is not required in the current state of the App. Hence i am closing this. Feel free to ask if you have any doubts. Thank you.
