### ISSUE TITLE
[UI-BUG]CarSelectionTextView is not updating. 

### ISSUE THREAD

**Issue by Piyusinha** [enviroCar/enviroCar-app#504]
CarSelectionTextView is not updating to "No Car type selected" after deleting all  cars from the car selection list.

**Comment by arvindnegi1** [comment]
@Piyusinha this issue is due to fragment not refreshing. Same issue exist for OBD selection. If you close and relaunch app again text view is updating. I attached PR for fragment not refreshing and this issue will automatically resolved.

**Comment by Piyusinha** [comment]
@arvindnegi1  Yes I know this but it should be update automatically without re-launching the app.

**Comment by arvindnegi1** [comment]
> @arvindnegi1 Yes I know this but it should be update automatically without re-launching the app.

i attached PR for fragment not refreshing this will fix this issue and it will automatically uploaded without relaunching.

**Comment by Piyusinha** [comment]
Thanks @arvindnegi1 but i already fixed this issue.

**Comment by arvindnegi1** [comment]
@Piyusinha it is great you fixed this issue but i mean that the PR i attached 4 days ago will fix this issue. #499 . Actually this PR solve 2-3 issue.
Thank you

**Comment by asaikarthikeya** [comment]
Duplicate #572

**Comment by SebaDro** [comment]
Thanks for reporting this issue. It has been also mentioned in #572 which was fixed with #573. Therefore I will close this issue.
