### ISSUE TITLE
Add more sign in option

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#509]
## Description
Currently users can only Sign in using credential used in registration with app, No other sign in option present.

# Expected
Different sign in option like <b>Sign in with Google</b><br><b>Sign in with Facebook</b>
which provide more flexibility to user.

**Comment by arvindnegi1** [comment]
@dewall Sir, i would like to work on this if you think its right doing so.

**Comment by dewall** [comment]
Since this would also apply adjustments on the server side, we don't want to implement these features right now.
