### ISSUE TITLE
Error Bluetooth device not discovering 

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#514]
## Description of Bug
Nearby Bluetooth device discovery not working in OBDII adapter selection while using the phone Bluetooth setting devices are discoverable.

**Comment by arvindnegi1** [comment]
@dewall sir, i found that this is because of ACCESS_COARSE_LOCATION permission not granted. Actually in my device it is not asking for permission i have to explicitly enable it from setting. 
Sir, how can we solve this?

**Comment by SebaDro** [comment]
Has been fixed with #753
