### ISSUE TITLE
Error Car selection process provides much flexibility to create artificial types of cars

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#519]
# Description of Bug
Currently, enviroCar android app Car selection process give much flexibility to user for simply type in attributes values or select from the data fetched from REST API. This selection process is prone to error as user can set undefined or non-existing values of car attributes and create artificial type of car which later lead to collection and processing of invalid data

## How i will fix
Integrating the previously defined datasets of vehicles  using Room database and change the UI with reference to new UI.
More detail can be found here : - https://blog.52north.org/2020/05/29/improvement-of-car-selection-process-in-the-envirocar-android-app/

**Comment by asaikarthikeya** [comment]
This was done as a part of GSoC 2020 right ? Can we close this issue @arvindnegi1 ?

**Comment by arvindnegi1** [comment]
Merged #527
