### ISSUE TITLE
Error icon and drop down icon overlap in car selection

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#521]
### Description of bug
In car selection autocompleteTextView error icon overlapping with drop down icon .

## Screenshot attached

<table>
<tr><th><h1>Error</h1></th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/33172321/84888175-8595a480-b0b4-11ea-9dd2-aad0e4ef6cd5.png" height=500 /></td>
</tr>
</table>

**Comment by harshkanjariya** [comment]
Can I Solve This Issue?
after solving this issue error will be shown like this :
[https://github.com/harshkanjariya/Testing/blob/master/file.jpg](url)

**Comment by dewall** [comment]
As you see, it has already been fixed and merged ;)

**Comment by asaikarthikeya** [comment]
@arvindnegi1  This works as expected but the error icon is not round in my mobile(might be because of error bound not exactly sure)

Error is in oval shape--
![Screenshot (Feb 1, 2021 3_36_18 PM)](https://user-images.githubusercontent.com/70392921/106444255-847a8180-64a3-11eb-94e2-c8692019be40.png)
