### ISSUE TITLE
Old workflow and UI design allow car selection on the basis of car attributes

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#526]
# Description of Bug
Old workflow and UI allow user to select car type using car attributes only.

## What is expected
A new workflow with new UI design. We know that user has two option to select car type. User can easily find car type using HSN/TSN or selecting appropriate car attributes consisting of manufacture,model,year. New workflow is required to allow switch between different mode.

## Initial UI Mockup (New Design)
<table>

<th>HSN/TSN</th>
<th> Car attributes</th>
<th>Car overview selection on basis of attributes</th>
<tr>
<td><img src="https://user-images.githubusercontent.com/33172321/86509020-7166dc80-be02-11ea-8970-8c82e86122e8.png" height=500>
</td>
<td><img src="https://user-images.githubusercontent.com/33172321/86509035-8a6f8d80-be02-11ea-8028-09100ef4a695.png" height=500>
</td>
<td><img src="https://user-images.githubusercontent.com/33172321/86509053-ae32d380-be02-11ea-8348-9a9a37225a74.png" height=500>
</td>
</tr>
</table>

**Comment by asaikarthikeya** [comment]
@arvindnegi1 Merged ! please close this PR ;)
