### ISSUE TITLE
Local track database layer is based on SqlBrite which has been depreceated

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#532]
## Description of issue
The local track database is based on SqlBrite. Since the square has deprecated and archived the SqlBrite repository, there will be no more support.

## What is expected
Newly created local Track database layer based on modern architecture component. We will shift our database to ensure support and to be flexible for the modern components. We will use a SQlite database with Room ORM.

**Comment by asaikarthikeya** [comment]
@arvindnegi1 Merged ! please close this PR ;)

**Comment by arvindnegi1** [comment]
Merged #533
