### ISSUE TITLE
Recording screen do not support Mirror View of layout

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#539]
## Description
Currently Recording screen layout does not has toggle to switch to Mirror View.
Mirror view can be very useful if user places phone on dash and can able to track measurements on Car front glass otherwise user has to pick up the phone which is highly distracting while driving.

**Comment by asaikarthikeya** [comment]
@arvindnegi1 Can we close this issue?

**Comment by arvindnegi1** [comment]
@asaikarthikeya the corresponding PR is not merged yet , actually after deleting gsoc2020 branch the PRs which are not merged are closed automatically. I need to open PR again to develop branch instead now.

**Comment by asaikarthikeya** [comment]
Oh. After you update the PRs. Lets request Sebastian Sir to review these PR.
