### ISSUE TITLE
Make ODB2 connexion optionnal 

### ISSUE THREAD

**Issue by arthurlutz** [enviroCar/enviroCar-app#547]
Hi, 

Project looks great and very promising. 

First quickly reading the website I did not understand that the collection side of things was GPS tracks *and* precise car data. I think that having two ways to contribute data, the first step being "just" the movement data, would already be quite useful to build an opendata dataset of traffic jams etc. The app would keep the ODB2 contribution as an option to go further for the people equipped with this kind of hardware. This would enable some users to start contributing while thinking about investing in this hardware to contribute more data. For the motivated I guess you could even have a "manual" entry such as "current level of gaz" which would give some indication of energy consumption. 

Hope this is not a duplicate request, and congrats for the app which looks really neat (no ODB2 device to test out)

**Comment by arvindnegi1** [comment]
Hi @arthurlutz ,
The app also support GPS based recording which can be enabled from settings section in the Others menu.
Also the repository has OBD simulator which can be installed in other device which mock the actual car adapter.

**Comment by SebaDro** [comment]
As @arvindnegi1 mentioned, a GPS only mode is supported which can be actviated in the settings. Hope, this meets your expectations. If not, feel free to reopen this issue.
