### ISSUE TITLE
Automatically select the car if only one car is added by user in 'My Cars' section

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#550]
### Description
Currently when the user has added a new car, he needs to do an additional step to select the car. 

### Expected
Automatically select the car , if there is only 1 car in the 'My cars' Activity.

**Comment by asaikarthikeya** [comment]
I am working on this issue.
@arvindnegi1

**Comment by Bhavya-22** [comment]
@asaikarthikeya  are you working on this issue. If not can you please allow me to work on it
