### ISSUE TITLE
Overlapping of cancel and pair device button

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#574]
**Actual Behaviour**

Overlapping of cancel and pair device button in the Bluetooth pairing .

**Expected Behaviour**

Gap between both button options.

![Screenshot_20210205-212047](https://user-images.githubusercontent.com/70392921/107057878-ed426080-67f9-11eb-8d69-01b1469f7ef7.png)

**I will work on this issue.**

**Comment by asaikarthikeya** [comment]
@arvindnegi1 Could you please share you thoughts on this issue. I tried my best to fix this.

**Comment by asaikarthikeya** [comment]
@arvindnegi1 Kindly comment your thoughts on this issue. I tried my best to fix this. Thank you.

**Comment by arvindnegi1** [comment]
@asaikarthikeya you can set layout params in one of the button i.e positive or negative button.

**Comment by asaikarthikeya** [comment]
Superseded by #747
