### ISSUE TITLE
Signup Activity Username shows error even after using just alphabets and underscore

### ISSUE THREAD

**Issue by pree-T** [enviroCar/enviroCar-app#576]
it
![1613285883371](https://user-images.githubusercontent.com/47977131/107870720-e0d89a80-6ec0-11eb-961e-6724a2c7988c.jpg)
 is showing that special symbols except underscore are not allowed even after using just underscore

**Comment by asaikarthikeya** [comment]
Works fine with me.No issue of such kind.

**Comment by AnandSidd** [comment]
The issue still persists and I am able to reproduce it.

It is showing Special symbols not allowed except underscore.
On using just underscore and no other special symbol used the error still shows.
![WhatsApp Image 2021-03-11 at 10 09 24](https://user-images.githubusercontent.com/54644440/110834348-4c105500-8252-11eb-9fed-893da07d7fc6.jpeg)
I am taking up this issue!!

**Comment by Bhavya-22** [comment]
@AnandSidd  if you are working on this issue or not as i am thinking of a solution to this issue and want to try but only you have no problem with it

**Comment by AnandSidd** [comment]
I have already made a PR to this issue,they haven't merged it still

**Comment by Bhavya-22** [comment]
In PR you have solve error to register one right

**Comment by AnandSidd** [comment]
Yes
