### ISSUE TITLE
Implement Navigation drawer 

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#578]
### **Description**

1) I would like to implement Navigation Drawer which contains  all the options of  "Others" in the bottom navigation . This helps user to quickly navigate to settings and other option .  

2) Add few more options such as shareapp .

**Comment by asaikarthikeya** [comment]
@bpross-52n  Sir, I want to work on this if you find it right doing so. Thank you :)

**Comment by bpross-52n** [comment]
Sure, can you share a preview or sketch of how this would look? Thanks!

**Comment by asaikarthikeya** [comment]
![submit](https://user-images.githubusercontent.com/70392921/108242490-fa087200-7172-11eb-9380-e2386ae2e74d.png)

This is a demo implementation will improve it .

**Things planned  --**
1) Navigation header containing envirocar log and logged in information .
2) All the "other" activity items are brought into navigation . 
3) Will add new features like shareapp etc. and group similar items in NavDawer.
 
I planned these things for now , would like to add more in the process .

@bpross-52n  please share you thoughts on this sir. Thankyou

**Comment by arvindnegi1** [comment]
@asaikarthikeya I personally don't like the mockup you have designed. I would better prefer bottom navigation that suits more to the current requirement. Also share app feature has been already implemented and pull request has been made.
Thank you ;)

**Comment by asaikarthikeya** [comment]
@arvindnegi1  I was not aware that app is converted from Navigation bar to Bottom Navigation bar in GSOC 2018 while creating this issue. Stopped working on this issue after going thought the advantages of Bottom navigation bar mentioned by 2018 Gsocer .Forgot to close the issue. Thank you
