### ISSUE TITLE
Dashboard Improvement .

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#581]
Expected --  Improve user navigation to other activities and solve bug(if any) in Dashboard.

I would like to break it down into separate PR's . Each PR is a sub task.

**Comment by asaikarthikeya** [comment]
#572 #566

**Comment by arvindnegi1** [comment]
@shivakanthsujit  you have already created the issue separately so no need to create issue again.

**Comment by asaikarthikeya** [comment]
> @shivakanthsujit you have already created the issue separately so no need to create issue again.

I thought it would be convenient & less time consuming if mentor could see all the workflow under one issue.
