### ISSUE TITLE
Make Alert-Dialog consistent across app

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#591]
Currently in the app there are 3 ways in which alert-dialog's are prompted to the user 

**1. No colour to toolbar and buttons**
<img src="https://user-images.githubusercontent.com/70392921/110356320-20c61400-8060-11eb-9dbb-41be48009a01.png" width="250" height="500"/> <img src="https://user-images.githubusercontent.com/70392921/110356328-21f74100-8060-11eb-8619-5807436e261c.png" width="250" height="500"/>

**2. Colour to only toolbar** 

<img src="https://user-images.githubusercontent.com/70392921/110356465-4d7a2b80-8060-11eb-9792-f8e1be990c84.png" width="250" height="500"/>

**3. Colour to both toolbar and buttons**

<img src="https://user-images.githubusercontent.com/70392921/110356397-3afff200-8060-11eb-946b-5cf5d71fb756.png" width="250" height="500"/>

### Excepted 
Implement all alert dialog in similar way. So that this improves Consistence.

I would like to implement the Alert dialog in as in 3rd Screenshot( Blue Colour to both toolbar and buttons)

**Comment by asaikarthikeya** [comment]
@bpross-52n Sir, i would like to work on this.

**Comment by SebaDro** [comment]
Implemented with merge of #747
