### ISSUE TITLE
Minor UI improvements

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#592]
1. As the background of the Signin and signup activity is Blue. It is hard to notice whether the particular input field is selected

![Photo from Sai Karthik (3)](https://user-images.githubusercontent.com/70392921/110357677-8cf54780-8061-11eb-8227-5fa3b93d2833.jpg)

2.  Estimated time --
![Photo from Sai Karthik](https://user-images.githubusercontent.com/70392921/110358072-fb3a0a00-8061-11eb-92b1-80da84c2f097.jpg)

**I will work on this issue.**

**Comment by vinayak0505** [comment]
what is the error in estimate time please elaborate

**Comment by asaikarthikeya** [comment]
> what is the error in estimate time please elaborate

I think 10:00 is hint to the user. This is should not be displayed when user starts to enter. Should reconfirm with mentor before doing. Thankyou.

**Comment by vinayak0505** [comment]
#593 changes issues resolved please check and let me know if you want something else
