### ISSUE TITLE
Floating action button hiding the radio button

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#598]
### **Description**

Floating action button hiding the radio button of car in Car selection activity.
 

<img src="https://user-images.githubusercontent.com/70392921/111028641-e4a70080-841d-11eb-85c8-615a7e8b3ea4.png" width="250" height="500"/>

**Comment by Droyder7** [comment]
Hello, can i work on this as my first issue?

**Comment by asaikarthikeya** [comment]
@Droyder7 Sorry, I have self assigned all the issues that i have opened. You are most welcomed to open new issues and work on them. Thank you.
