### ISSUE TITLE
Register here and Sign In here as plain text

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#600]
**Issue:-** As register here and Sign in here are simply plain text so it doesn't giving a good response whether it is clicked or not. As a user point of view, if he/she has network issues then it will be unable to understand whether app has a issue or net.

**How will I fix this:-**

I will make sign in here and register here as button suitable with the colour codes of app so it will look more responsive to user as button clicked can be seen also it is convenient as most Login/SignUp page has button for this generally.  Also i will make above text to Register,signin text as white so it will look more clearly on blue background

![Login Page](https://user-images.githubusercontent.com/54673703/111272228-5074ad80-8658-11eb-91c8-3f8db91ffa62.jpeg)
![SignUp Page](https://user-images.githubusercontent.com/54673703/111272234-51a5da80-8658-11eb-83ad-ad1cef3f3a9b.jpeg)

**Comment by rohittrimalle** [comment]
i can work on this issues

**Comment by rohittrimalle** [comment]
i can contribute on this issue

**Comment by rohittrimalle** [comment]
i want add animation on button anyone guide me
![Capture](https://user-images.githubusercontent.com/65027928/111431945-69499580-8722-11eb-85cd-fa10f3f0473c.PNG)
![Capture1](https://user-images.githubusercontent.com/65027928/111431974-71093a00-8722-11eb-9da7-0d298cd4516e.PNG)

**Comment by Bhavya-22** [comment]
@rohittrimalle Basically I am going to solve it by myself. Now I am having my academic exams that's why i am unable to work right now. Although thank you for showing interest in this issue as you have almost done it so please let me know what animation are you trying to add. If i know it then i can add that part along with mentioning your work to PR so both are able to create a PR reagrding this.

**Comment by Bhavya-22** [comment]
PR for this has been created.
https://github.com/enviroCar/enviroCar-app/pull/628

**Comment by Bhavya-22** [comment]
@rohittrimalle  see that in your work there are shadows behind sign in here and register here also after making sign in here as button/cardview you didn't make the background as one there are two backgrounds behind them. And you forget to add space between register here and the text above it.
For now I made the PR with this improvements but I hope my comment will be useful for you

**Comment by asaikarthikeya** [comment]
In all the popular apps. The register here/ create new account buttons is always present in text form. Eg - Instagram, Facebook etc..Hence, I am closing this issue. feel free to ask if you have any doubts. Thanks for sharing your thoughts @Bhavya-22 ;)

**Comment by Bhavya-22** [comment]
But atleast make them focusable so that when user click the click can be observed/feel

**Comment by asaikarthikeya** [comment]
Whole sign in and Sign up activities need to be completely redesigned. Sometime in the future.
