### ISSUE TITLE
Make SignIn Page and SignUp more responsive

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#601]
**Issue:-** Firstly, Edit text indicator is also blue in colour so because of that it is unable to know whether a particular edit text is selected or not. Also nothing happen to hints in edittext when they are selected by which also user can't find it more responsive.

**How will I fix this;-** Firstly make indicator colour white so that when edit text selected it can be seen and for more better improvements i will add highlighted hint option by which on selection hint will become heading of that edit text.

![Login_indicator](https://user-images.githubusercontent.com/54673703/111273711-2623ef80-865a-11eb-9779-6101a10be878.jpeg)

**Comment by asaikarthikeya** [comment]
Duplicate #592

**Comment by Bhavya-22** [comment]
@asaikarthikeya you are working on indicator only or also going to work on edit text to make it more responsive

**Comment by Bhavya-22** [comment]
Basically i was thinking to work on indicator as well as edit text if you are working on indicator only then please let me know so that i will work on edit text improvements part if it's ok with you.

**Comment by asaikarthikeya** [comment]
Edit text improvement meaning ? Do you want to remove hint when indicator is on the edittext?

**Comment by ritish099** [comment]
can i work on this issue ?

**Comment by Bhavya-22** [comment]
> Edit text improvement meaning ? Do you want to remove hint when indicator is on the edittext?

No I want to improve a little bit so that on touch it can be feel more responsive.(I am not going to remove hint but update hint part a little bit)

**Comment by Bhavya-22** [comment]
@asaikarthikeya let's do one thing you will update the indicator part and I will update the edit text part

**Comment by asaikarthikeya** [comment]
@Bhavya-22  #603 Done from my side :)

**Comment by Bhavya-22** [comment]
> @Bhavya-22  #603 Done from my side :) 

👍

**Comment by asaikarthikeya** [comment]
@Bhavya-22  I have mailed you .Kindly checkout Thank you

**Comment by Bhavya-22** [comment]
PR for this is created #680
Also as I mentioned in PR comment I have not made indicator white. As @asaikarthikeya has made that in one of it's PR (#603) as mentioned in above comments.

**Comment by Bhavya-22** [comment]
@arvindnegi1 Sir please review #680 regarding this issue.

**Comment by asaikarthikeya** [comment]
@Bhavya-22 Curser is done in #777 and about the enhancing the hints, Google made hints intentionally low in colour, so that these doesnot look as text inside the edittext. It is understandable if the edittext hints are low in colour. Thanks for sharing your views ;)
