### ISSUE TITLE
Show error in Username in SignIn page when other then underscore ( _ ) any special character is used and make Uppercase error free. Add show password option.

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#604]
**Issue:-** Although it is showing error in Username field in Register Page about other special characters other than underscore but it is not showing error for the same in SignIn page.  Also password cannot be shown in sign in page which can be a trouble to user as for confirmation of password user generally prefer to show what they wrote.

**How will I fix this:-** I will show an error message that "this username is not valid" when other than underscore any other special character is used. Also I will allow Uppercase in Username field to be error free. (As to make Uppercase  error free in register PR is already made by @AnandSidd so I will not change the error code for register page by myself ). I will add show password icon in password edit text with gap between the error icon and password icon to be included.

![Error_username](https://user-images.githubusercontent.com/54673703/111330667-293cd100-8696-11eb-9f24-d727bdccb193.jpeg)

**Comment by Bhavya-22** [comment]
PR for this is created
#689

**Comment by asaikarthikeya** [comment]
duplicate #482
