### ISSUE TITLE
Dialog buttons view collapsing with each other

### ISSUE THREAD

**Issue by rahulshah456** [enviroCar/enviroCar-app#606]
### Description
Dialog buttons in the Bluetooth pairing screen are collapsing with each other as the padding between the views is not enough.

### Screenshot
![Screenshot_20210316-225545 1 (1)](https://user-images.githubusercontent.com/41780639/111356706-a116f580-86ae-11eb-95cc-9a85ce20f231.png)

### Expected
Both the buttons should be separated by enough margins to look distinguishable.

### Like to work on the issue?
Yes, I would like to work on this issue.

**Comment by asaikarthikeya** [comment]
Duplicate #584

**Comment by rahulshah456** [comment]
Okay then I will close this issue @asaikarthikeya
