### ISSUE TITLE
App Crash while Navigating to CarRadiobutton

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#609]
**Actual Behaviour**

After we login , Clicking on Car Radiobutton(in Dashboard) / CarselectionFragment app crashes.
I loged out , This issue still persists 

**Expected Behaviour**

Should navigate to Car selection activity.

https://user-images.githubusercontent.com/70392921/111410848-8456de00-86ff-11eb-98c0-87846a9cc5ec.mp4

**Comment by asaikarthikeya** [comment]
Hello @arvindnegi1 , Are you able to reproduce this issue?

**Comment by rohittrimalle** [comment]
that issue on emulator not on mobile

**Comment by asaikarthikeya** [comment]
> that issue on emulator not on mobile

I am using mobile only.

**Comment by rohittrimalle** [comment]
i don't get that issue on mobile

**Comment by arvindnegi1** [comment]
@asaikarthikeya Sorry I can't able to reproduce. Please check you has not made changes.

**Comment by asaikarthikeya** [comment]
@arvindnegi1 I think this issue is same as #423 . Thankyou

**Comment by asaikarthikeya** [comment]
![Screenshot from 2021-05-21 19-08-54](https://user-images.githubusercontent.com/70392921/119146218-0c42c680-ba68-11eb-9bf8-4ce53058ce31.png)

**Comment by asaikarthikeya** [comment]
@arvindnegi1 Kindly look at the screenshot. I am able to reproduce this issue, NullPointerException
