### ISSUE TITLE
Bug: The bluetooth, GPS etc buttons

### ISSUE THREAD

**Issue by ritish099** [enviroCar/enviroCar-app#611]
Once the Bluetooth, GPS buttons are turned ON . Again clicking on the button doesn't turn it off.

**Explanation of issue:**
Open the app and go to the above screen. Turn on Bluetooth or GPS by clicking on the respective icon. Once they are turned On. They will turn into blue clour. Now try again clicking on that icon to turn off the feature(Bluetooth or GPS or other) the button will not respond.

**Expected Behavior:**
Button Should response and turn off the Bluetooth or GPS or etc whichever clicked on

**ScreenShot**
<img src="https://user-images.githubusercontent.com/54978105/111439533-7ae36b00-872b-11eb-9e61-96cc1e6d0784.jpg" width ="333">

**Comment by ritish099** [comment]
I am Working on it

**Comment by asaikarthikeya** [comment]
@ritish099 Can you please elaborate the issue. Thank you

**Comment by ritish099** [comment]
Open the app and go to the above screen. Turn on Bluetooth or GPS by clicking on the respective icon. Once they are turned On. They will turn into blue clour. Now try again clicking on that icon to turn off the feature(Bluetooth or GPS or other) the button will not respond.
Expected Behavior:
Button Should response and turn off the Bluetooth or GPS or etc whichever clicked on

**Comment by asaikarthikeya** [comment]
> Open the app and go to the above screen. Turn on Bluetooth or GPS by clicking on the respective icon. Once they are turned On. They will turn into blue clour. Now try again clicking on that icon to turn off the feature(Bluetooth or GPS or other) the button will not respond.
> Expected Behavior:
> Button Should response and turn off the Bluetooth or GPS or etc whichever clicked on

This is intentionally done so.

**Comment by asaikarthikeya** [comment]
We would prefer them to be ON while using the app. So, the mentors intentionally made it unresponsive if they are on.

**Comment by ritish099** [comment]
If we want the user to turn on Bluetooth and other features while using the app. Then we can just simply turn them on whenever they open the app(You can see this feature in  many production apps) but if we are giving user the liberty to Turn ON then i think he/she should have the liberty to turn it OFF. The user might just want to use Bluetooth and not GPS. Or any combination of features.

**Comment by ritish099** [comment]
Either we should Turn all the features ON automatically whenever the user opens the app. or we should give him the liberty to turn off some features if we are giving him/her liberty to turn it ON

**Comment by asaikarthikeya** [comment]
Good points.Work after the mentor confirms this issue :)

**Comment by ritish099** [comment]
Ok

**Comment by ritish099** [comment]
Can you mention the mentor ?

**Comment by Bhavya-22** [comment]
@bpross-52n is the mentor for enviroCar project

**Comment by ritish099** [comment]
@Bhavya-22 thanks

**Comment by Bhavya-22** [comment]
Also you can mention @arvindnegi1 sir as he is also one of the contributors or you can see contributors list and tag according. But for Gsoc point of view @bpross-52n is mentor for this

**Comment by asaikarthikeya** [comment]
Merged into the master branch!
