### ISSUE TITLE
Bug: No checking for empty field in Confirm Password field in Signup activity

### ISSUE THREAD

**Issue by ritish099** [enviroCar/enviroCar-app#613]
Fix #613 
No checking for the empty field in Confirm Password field in the 
Signup activity. As it is present for other fields in that activity

**ScreenShot**
<img src="https://user-images.githubusercontent.com/54978105/111441797-aebf9000-872d-11eb-859a-cb8533c07175.jpg" width ="333">

**Comment by ritish099** [comment]
I am working on this

**Comment by Bhavya-22** [comment]
@ritish099 you added the error icon right. Or you added the gap between the icon and eye icon too. If you have not added then please let me know as i am working it for password so i will make sure for confirm password field too.(I will just add your files in my computer and mention that error icon is added by you what i will do is to ensure the gap between both icons in my PR regarding this issue).
Please let me know about this.

**Comment by ritish099** [comment]
@Bhavya-22 I didnt wrote any code to add gap between the error icon and eye icon as u can see my PR. I only added validator for Confirm Password Feild. U can proceed with it

**Comment by Bhavya-22** [comment]
@ritish099 ok thank you for the information I will mention in my PR about your explicit icon
