### ISSUE TITLE
Feature: Open Web Links inside the app

### ISSUE THREAD

**Issue by ritish099** [enviroCar/enviroCar-app#614]
As followed in most of the modern apps. Clicking on web links should open the link inside the app without needing to exist the app

**Observed Behaviour**
Clicking on weblink open a web browser 

**Expected Behaviour**
As in modern apps. The link should be open inside the app.

**ScreenShot**
<img src="https://user-images.githubusercontent.com/54978105/111444432-5fc72a00-8730-11eb-8f2a-7eeca6a327dc.jpg" width ="333">

**Comment by ritish099** [comment]
I am working on it

**Comment by ojasjain24** [comment]
I will work on this @bpross-52n

**Comment by ojasjain24** [comment]
I have resolved this issue. I have used WebView to show website in the app and SpannableString to set the OnClickListner on the link part of the TextView. @bpross-52n
