### ISSUE TITLE
Text not visible due to bad color scheme.

### ISSUE THREAD

**Issue by swayamkaul** [enviroCar/enviroCar-app#625]
"Do you already have an account?" text is not clearly visible due to it's color in the SignUp activity.
![Screenshot 2021-03-19 at 1 11 21 AM](https://user-images.githubusercontent.com/43716674/111693880-305f0d00-8857-11eb-886b-cdf3e52883c9.png)

Similar is the case with SignIn activity.
![Screenshot 2021-03-19 at 1 12 26 AM](https://user-images.githubusercontent.com/43716674/111694065-6603f600-8857-11eb-95e6-22d01dc9ec08.png)

**Comment by swayamkaul** [comment]
I am working on this.

**Comment by Bhavya-22** [comment]
@swayamkaul I have mentioned it in my issue #600 and I am working on it right now
