### ISSUE TITLE
Logbook:- Kommentar text change. Add message for successful add fueling

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#630]
**### Issue** :- After opening logbook it is just showing a blue button but there is no sign in it(+ sign to signify add). Also for general app it is showing kommentar not Comments. And there is no confirmation regarding successfully fueling added .

**How I will fix this**:- I will add a + sign in that button in white colour so that it can be seen easily. Also make kommentar as comments in general string file. And add a snackbar/toast for successfully fueling added.

![Comment_LogBook](https://user-images.githubusercontent.com/54673703/111896852-614f6580-8a42-11eb-8add-0e79c14a545f.jpeg)
![Button_Logbook](https://user-images.githubusercontent.com/54673703/111896855-63192900-8a42-11eb-9ca1-ae79da6fc8ba.jpeg)

**Comment by Bhavya-22** [comment]
I will be working on this

**Comment by asaikarthikeya** [comment]
#607 This PR adds the Floating action . Please refer to previous issues and open Pull requests before opening a issue. thank you.

**Comment by Bhavya-22** [comment]
Ok if in #607 plus icon work is done so I will do the rest as I mentioned in my PR

**Comment by arvindnegi1** [comment]
@Bhavya-22 you can change the string file but please don't forget to change the translated string.

**Comment by Bhavya-22** [comment]
@arvindnegi1 sir I will implement string English version at place ok kommentar not going to delete kommentar value just going to change the Id and string in eng version(if needed) to make it comment

**Comment by arvindnegi1** [comment]
> @arvindnegi1 sir I will implement string English version at place ok kommentar not going to delete kommentar value just going to change the Id and string in eng version(if needed) to make it comment

I mean add string id in english version and also add corresponding german version with same id in values-de strings_logbook
thanks!

**Comment by Bhavya-22** [comment]
Ok sir I will do it accordingly tha k you for your guidance.

**Comment by Bhavya-22** [comment]
Sir is it alright to use strings/values send_log_comments_label by this first it is not hard coded now and I have not changed any de strings values

**Comment by Bhavya-22** [comment]
@arvindnegi1 sir when we delete a fueling the snack bar text "fueling is successfully deleted from server" is showing but I think as a user point of view from server is not necessary so can I edit this text too or just let it be as it is

**Comment by Bhavya-22** [comment]
> @arvindnegi1 sir when we delete a fueling the snack bar text "fueling is successfully deleted from server" is showing but I think as a user point of view from server is not necessary so can I edit this text too or just let it be as it is

Or if from server should not be deleted so should I add the same to successful Snack bar text also (Your fueling is successfully added to server or just your fueling is successfully added).

Please let me know so that no comments on review is required.(or I can just change both delete and add text and you can review it on PR)

**Comment by Bhavya-22** [comment]
PR for this is created 
#672 
@arvindnegi1 Sir please review it and also let me know about the comment I wrote.

**Comment by Bhavya-22** [comment]
For now i have added the "to server" text to successful adding fueling snackbar too.
