### ISSUE TITLE
SignUp Activity :- Make gap between error showing in password and show password icon.Also make show icon colour different

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#632]
**Issue** :- When there is error showing for password the error icon and show password icon are coinciding. Also show icon cannot seen properly in both password and confirm password.

How will I fix this** :- I will add gap between the error and eye icon. Also add colour to icon so that it can be seen more clearly.

![Register_Icons](https://user-images.githubusercontent.com/54673703/111897890-8fd03f00-8a48-11eb-813c-bfd5e44905e4.jpeg)

**Comment by Bhavya-22** [comment]
I will be working on this and if #613 by @ritish099 is done completely and correctly then i will add gap for that icon too for confirm password.

**Comment by asaikarthikeya** [comment]
#571

**Comment by Bhavya-22** [comment]
@asaikarthikeya you have made the gap between both icons

**Comment by asaikarthikeya** [comment]
Yes I did :)

**Comment by Bhavya-22** [comment]
So I will do the icon part only then
