### ISSUE TITLE
SignUp Activity:- Enhance eye icons visibility. 

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#634]
**Issue** :- In SignUp Activity confirm password as hint and error icon is showing only when eye icon or show password icon is clicked two times.

**How will I fix this** :- Firstly i will show confirm password complete as hint without click also and as @ritish099 added error icon in normal case. So I am not going to work for error to show(in normal case). And make both eye icons a little darker so that it can be seen clearly.

https://user-images.githubusercontent.com/54673703/111907403-287fb280-8a7b-11eb-9aac-0119d92c42cc.mp4

**I will be working on this issue**

**Comment by arvindnegi1** [comment]
duplicate #570

**Comment by Bhavya-22** [comment]
@arvindnegi1 sir it is not duplicate as I am not going to make gap between password edit text but I am doing it for confirm password edit text also going to edit dimension so that confirm password as hint can be seen directly.
@asaikarthikeya have made gap for password only I am doing it for confirm password field with one more thing to modify as mentioned above.

I hope I am able to clear the query regarding this

**Comment by Bhavya-22** [comment]
Sir you can see the screen recording which I have uploaded for reference so it will be more cleared.

**Comment by asaikarthikeya** [comment]
@Bhavya-22 That PR solves that also.

**Comment by asaikarthikeya** [comment]
@Bhavya-22  Screenshot from that branch.It adds error gap for Confirm password too.

![Screenshot (Mar 21, 2021 10_20_09 PM)](https://user-images.githubusercontent.com/70392921/111913414-00e91400-8a94-11eb-886a-cb2470e912d0.png)

**Comment by asaikarthikeya** [comment]
If you wish to reduce the font size, Open another issue mentioning that. Kindly,Maintain same font size for all the hint.

**Comment by Bhavya-22** [comment]
@asaikarthikeya  in your screenshot changes is showing for password only have to made the gap for confirm password too

**Comment by Bhavya-22** [comment]
> If you wish to reduce the font size, Open another issue/ edit this issue mentioning only about fonts. Kindly,Maintain same font size for all the hint.

Yes I will first see if by same font is it possible or not and if not i will either change dimension of text or font size accordingly

**Comment by asaikarthikeya** [comment]
> @Bhavya-22 Screenshot from that branch.It adds error gap for Confirm password too.
> 
> <img alt="" width="250" height="500" src="https://user-images.githubusercontent.com/70392921/111913414-00e91400-8a94-11eb-886a-cb2470e912d0.png">

....

**Comment by asaikarthikeya** [comment]
Please see the Screenshot @Bhavya-22

**Comment by Bhavya-22** [comment]
@asaikarthikeya ok so gap is made between these two also so I will just change edit text so that confirm password hint and error cannot coincide

**Comment by Bhavya-22** [comment]
@arvindnegi1 sir I have a doubt firstly if gap is made by you in both password and confirm password then how #570 is not duplicate and secondly if it got merged then why the error is still showing like this as in your screenshot they are align to each other completely and in my screenshot there is some part coinciding only although I will also going to fix the same as you mentioned in your PR but maybe if possible with a more gap.

So sir please let me know about this.

**Comment by arvindnegi1** [comment]
@Bhavya-22 actually it works perfectly fine with my device but as seen from the reference of issue created again this means their is still little overlap. So you need to think for something that can be consistent with every device. Changing the error bounds is ugly workaround as because I previously used 50 so changing it 70 can lead to huge gap. That's why I didn't approve that pull request. I marked this as duplicate as the issue has been already created and only one issue can reference the particular bug but Please think of exactly how can we fix this.
Thanks!

**Comment by Bhavya-22** [comment]
> @Bhavya-22 actually it works perfectly fine with my device but as seen from the reference of issue created again this means their is still little overlap. So you need to think for something that can be consistent with every device. Changing the error bounds is ugly workaround as because I previously used 50 so changing it 70 can lead to huge gap. That's why I didn't approve that pull request. I marked this as duplicate as the issue has been already created and only one issue can reference the particular bug but Please think of exactly how can we fix this.
> Thanks!
> 
>  

So sir basically you have created a gap that runs fine in your device but in mine it is coinciding a little bit and for @asaikarthikeya too so he created that gap again or improved your version but did he improve only for password or for both that's my last question regarding this.

If gap is improved for both then I will edit my work/issue and if it is improved for password only then I would like to improve that for confirm password text.

So, please let me know the exact scenario regarding the icons gap for both fields. So I can work accordingly.

Thank you and Regards. And sorry if I trouble you by asking again and again

**Comment by Bhavya-22** [comment]
Sir I think what I get from seeing your file and @asaikarthikeya is he changed values from 50 to 70/75 but it will create huge gap in your phone so the issue is same here also with confirm password but I cannot solve because of #570 as same issue but sir if I get any idea that how can we resolve this so I should make a PR for 570 or I can do this in my issue. Or I should tell the solution to @asaikarthikeya for his issue if I get one.

**Comment by arvindnegi1** [comment]
@Bhavya-22 yeah i already said this is just a ugly workaround. We need to think of proper solution to this. You can close this PR and yes you can create your own PR referring to that issue because we didn't get exact solution.

**Comment by Bhavya-22** [comment]
So sir instead of closing it I think I should remove that gap thing for now and work on other two aspects.

**Comment by Bhavya-22** [comment]
PR for this is created #684.
