### ISSUE TITLE
Add icon to make Password visible in sigin.

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#635]
User has no way to check whether he entered a correct password or not.

![Screenshot_20210321-194556](https://user-images.githubusercontent.com/70392921/111908181-426ec480-8a7e-11eb-84f8-cf9033b6b848.png)

**Comment by Bhavya-22** [comment]
@asaikarthikeya  I mentioned this in my issue #604 and I am working on this
