### ISSUE TITLE
Blank page when no cars are added.

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#636]
When No cars are added, We could set the background to "No cars added" with a image. 

<img src="https://user-images.githubusercontent.com/70392921/111908336-dc367180-8a7e-11eb-9f18-b28a8720bb88.png" width="250" height="500"/>

**I will work on this issue.**

**Comment by niish03** [comment]
@asaikarthikeya Thanks for the attention , I have solved your issue . Thank you ;)

**Comment by asaikarthikeya** [comment]
@niish03 I was working on this issue. Please confirm the issue before working on it

**Comment by asaikarthikeya** [comment]
> @asaikarthikeya Thanks for the attention , I have solved your issue . Thank you ;)

How ? Copy and pasting the previous Gsocer work ?

**Comment by asaikarthikeya** [comment]
fixed by #770
