### ISSUE TITLE
Improvements in Settings Dialog

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#637]
**Issue** :- There is no gap between cancel and ok button in all setting dialog box. Also there is very less spacing between minutes and seconds selector for Discovery Interval and Track trim Duration. Also bar is scrolling at a point not scrolling completely.

**How will I fix this** :- Firstly make dialog box a little bigger so that gap  between selectors can be made and seen clearly. Also add gap between both the buttons. As @asaikarthikeya are working to make them colour so I am not working on to add colours to button.  Also i will add colour to selector lines  and improve scrolling for both minutes and seconds.

https://user-images.githubusercontent.com/54673703/111908783-94184e80-8a80-11eb-897c-28078aea2388.mp4

**I will be working on this issue**

**Comment by asaikarthikeya** [comment]
#591 Actually there are 2-3 ways in which Dailogs are implemented across the app. I am waiting for the mentors thoughts. I have planned to change the colour+ design of alert dialog's as mentioned in the tagged issue. Thank you.

**Comment by Bhavya-22** [comment]
@asaikarthikeya you want to make consistent dialog box for whole app in this I am improving time picker and just adding gap and making selector lines blue. So i am trying to improve existing dialog box not going to change its design so if your feature is confirmed by mentor then you can change design for this dialog box also.
Hope you understand my point.

**Comment by Bhavya-22** [comment]
PR for this is created 
#685 
@arvindnegi1 @bpross-52n Sir please let me know if I can create customise Dialog (specially for buttons) or DialogPreference is used for a reason. And if @asaikarthikeya idea for #591 is approved then i have no issue if @asaikarthikeya make the alert dialog box for settings also.
**Please let me know about this**

**Comment by asaikarthikeya** [comment]
@SebaDro Implemented by merge of #747
