### ISSUE TITLE
Indicator not clickable after selection

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#639]
**Describe the bug**
Indicator clicked after selection does not redirect to corresponding functionality .

**To Reproduce**
1. Open dashboard fragment.
2. If Indicator is already marked on click nothing happened.

**Expected behavior**
On different indicator clicked even after selection redirects to corresponding functionality.

**Comment by arvindnegi1** [comment]
Anyone can work on this. Please ask before solving.

**Comment by ojasjain24** [comment]
I will work on thia @arvindnegi1 . Please assign me this task

**Comment by arvindnegi1** [comment]
@ojasjain24 You can work on this. Please let me know if you stuck.
Thanks!

**Comment by asaikarthikeya** [comment]
@arvindnegi1 Duplicate #611

**Comment by arvindnegi1** [comment]
@ojasjain24 Sorry, this issue has been already raised.
I'm closing this.
