### ISSUE TITLE
Toggle button in Adapter Selection does not change state on deny

### ISSUE THREAD

**Issue by arvindnegi1** [enviroCar/enviroCar-app#640]
**Describe the bug**
On trying to enable bluetooth from the app the toggle button does not change it state to off if we click on deny on anywhere on screen.

**To Reproduce**
1. Click on OBD selection in Dasboard fragment.
2. Click on toggle button.
3. Click on deny or anywhere on screen.
4. Toggle button switches to ON state rather it should be in off state if deny or nothing is selected.

**Expected behavior**

Reset toggle button to off state if no selection is made or deny is clicked. Also we can add ON /OFF instead of simple toggle button.

**Comment by arvindnegi1** [comment]
Anyone can work on this. Please ask before solving.

**Comment by asaikarthikeya** [comment]
@arvindnegi1 I will work on this.

**Comment by ojasjain24** [comment]
can I work on this @arvindnegi1 ?

**Comment by arvindnegi1** [comment]
@asaikarthikeya You can work on this.
Thanks!

**Comment by SebaDro** [comment]
Fixed with #734
