### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ojasjain24** [enviroCar/enviroCar-app#641]
When we delete a car that was selected, It must get deleted from Dashboard fragment. But Its still there. For example I have no cars but its showing previously selected car (now deleted).
![WhatsApp Image 2021-03-21 at 11 21 56 PM](https://user-images.githubusercontent.com/59116312/111915839-385cbe00-8a9e-11eb-9191-13944bbac0e5.jpeg)
![WhatsApp Image 2021-03-21 at 11 31 30 PM](https://user-images.githubusercontent.com/59116312/111915862-47437080-8a9e-11eb-91d8-b2aab6f2a69a.jpeg)

**Comment by asaikarthikeya** [comment]
duplicate #572

**Comment by ojasjain24** [comment]
Duplicate
