### ISSUE TITLE
"Support by develop" option

### ISSUE THREAD

**Issue by ojasjain24** [enviroCar/enviroCar-app#642]
we can add a develop option in 'others Fragment' , which will lead the user to the GitHub repository of the project.
@arvindnegi1 shell I work on this?

**Comment by arvindnegi1** [comment]
@ojasjain24 You can do that. The maintainer will look into this if this is required.

**Comment by ojasjain24** [comment]
I have resolved this issue

**Comment by asaikarthikeya** [comment]
This is enhancement is not required with the current app. Thank you @ojasjain24 for sharing your thoughts.
