### ISSUE TITLE
"send feedback" option will improve ux

### ISSUE THREAD

**Issue by ojasjain24** [enviroCar/enviroCar-app#644]
adding a option to send feedback/ suggestions will improve users experience. email should open when user clicks on the option.
I will work on this.

**Comment by ojasjain24** [comment]
I have resolved this issue

**Comment by Bhavya-22** [comment]
@ojasjain24  have you made the webView for help point 5 Problems and Feedback option in which enviroCar@52north.org is not clickable. If you made the webView or to open website directly from browser after clicking it then please let me know and if not I am going to create this issue. So if you have worked on it then I will not create it otherwise I will make that site clickable to open it.
Please let me know about this.

**Comment by arvindnegi1** [comment]
@ojasjain24 it has rate us feature already and anyone can publicly provide feedback in PlayStore.

**Comment by Bhavya-22** [comment]
@arvindnegi1 Sir can you let me know whether in this issue the gmail id is make clickable or not to open gmail or any other mail app directly with To option contains the enviroCar gmail
If its not then please let me know as i will create a issue for this and make the PR regarding that

**Comment by ojasjain24** [comment]
@Bhavya-22 I have given an option "send feedback/ suggestion" in "others fragment" below "rate us". So it doesn't deal with mail id link. When we click on that option, Mail will open in Gmail, not inside app.

**Comment by arvindnegi1** [comment]
@Bhavya-22 issue #457

**Comment by ojasjain24** [comment]
@arvindnegi1, In help section, in point number 5, Its written "We welcome your feedback (enviroCar@52north.org)! ... ". So, that's the reason I gave this option.

**Comment by Bhavya-22** [comment]
> @Bhavya-22 I have given an option "send feedback/ suggestion" in "others fragment" below "rate us". So it doesn't deal with mail id link. When we click on that option, Mail will open in Gmail, not inside app.

So isn't it better to make mail clickable in help option then this.

**Comment by Bhavya-22** [comment]
> @Bhavya-22 issue #457 

So sir the pr for this is made or I can work on this issue as the issue created 1 year ago

**Comment by asaikarthikeya** [comment]
> @ojasjain24 it has rate us feature already and anyone can publicly provide feedback in PlayStore.

This is a valid point from @arvindnegi1. Currently app has rate feature to provide feedback and report issue to report bugs. Adding more options to rate/give feedback is not required as of now. Thank you for your contribution @ojasjain24. Feel free to ask, if you have any more doubts.
