### ISSUE TITLE
add animated icons in Bottom navigation

### ISSUE THREAD

**Issue by Patel-Hemant** [enviroCar/enviroCar-app#645]
make bottom-navigation icons animated when we click any item of navigation. That makes UI good.
![2021-03-16_21-45-19](https://user-images.githubusercontent.com/59821647/111945433-bbfac700-8aff-11eb-97f9-e3f001c13282.gif)

this is an example of the idea.
![2021-03-17_12-28-43](https://user-images.githubusercontent.com/59821647/111944377-85bc4800-8afd-11eb-9abb-5fe92c1f2989.gif)

**Comment by Hemu43362** [comment]
I am working on this.
