### ISSUE TITLE
Email Regex fails to match hyphen in domain name

### ISSUE THREAD

**Issue by mvoggu** [enviroCar/enviroCar-app#654]
`f20180564@hyderabad.bits-pilani.ac.in` is a valid email address, but the current Regex for email does not allow it because of a hyphen(-) in the domain name

I propose that we follow the regex suggested in https://stackoverflow.com/a/201378

**Comment by mvoggu** [comment]
@arvindnegi1 as this particular issue can also be fixed by allowing hyphen in the current regex without shifting to the proposed one, I want to know your thoughts on this before submitting a PR

**Comment by arvindnegi1** [comment]
@mvoggu Yes you can allow hyphen before the @ part. 
thanks!
