### ISSUE TITLE
Blank UI when there is no cars in list.

### ISSUE THREAD

**Issue by niish03** [enviroCar/enviroCar-app#655]
When No cars are added, We could set the background to "No cars added" with a image.
![Screenshot_20210323-003630.jpg](https://user-images.githubusercontent.com/61544937/112044429-d4a2c580-8b6f-11eb-8274-c0b748a6a37b.jpg)

**Comment by asaikarthikeya** [comment]
This was implemented in as a part of last year GSOC. That pull request was merged. DUPLICATE

**Comment by niish03** [comment]
Kindly check above mentioned PR , i have managed all the checks cases inclued , "when list is empty it will shoe opps msg and when link is not empty it will hide the layout."

**Comment by asaikarthikeya** [comment]
It was done in previous year gsoc. No need to copy previous GSoC'er work and send it to master.

**Comment by asaikarthikeya** [comment]
Duplicate #636
