### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ojasjain24** [enviroCar/enviroCar-app#656]
when I'm clicking on Start Track button in dashboard fragment, its showing a dialog box displaying a message "Trying to find 'device Bluetooth id'" . after that nothing happens. Is it occurring  only in my device or others are also facing this issue?

**Comment by asaikarthikeya** [comment]
@ojasjain24 Please add screen recording. Thankyou.

**Comment by ojasjain24** [comment]
https://user-images.githubusercontent.com/59116312/112046810-80e5ab80-8b72-11eb-93e9-3c1aecabb16b.mp4

**Comment by asaikarthikeya** [comment]
Your Bluetooth device doesn't contain OBD Simulator, we need simulator to start tracking.

**Comment by ojasjain24** [comment]
Okay. Thanks for the help😊

**Comment by asaikarthikeya** [comment]
@ojasjain24  Please go though the README.md for more information. We could close this issue if you are clear about this :)

**Comment by ojasjain24** [comment]
yeah sure!
