### ISSUE TITLE
App guide for new users.

### ISSUE THREAD

**Issue by ojasjain24** [enviroCar/enviroCar-app#657]
A guide will improve UX. A guide that will show all the features and functionalities to the first time users, which is skippable.

@bpross-52n what are your thoughts about this?

**Comment by asaikarthikeya** [comment]
This was added by @arvindnegi The PR is open.Yet to be reviewed.
DUPLICATE

**Comment by ojasjain24** [comment]
Duplicate

**Comment by ojasjain24** [comment]
@asaikarthikeya can you please share pull request number?

**Comment by asaikarthikeya** [comment]
#537
