### ISSUE TITLE
New Feature:- Bluetooth and Location permission

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#660]
**Issue**:- If bluetooth is off we need to enable it again and again. Same for the location/GPS too

**How wiil I fix this** :- Instead of asking again and again we can just ask after installation to allow bluetooth,location permission. So after this if bluetooth,location is off the user just need to on it from settings and it will show on in enviroCar app. 

**I will work on this issue if it is acceptable**

**Comment by Bhavya-22** [comment]
@arvindnegi1, @bpross-52n sir please let me know if i should implement this feature or not

**Comment by asaikarthikeya** [comment]
User should be able to continue to use the app without these permissions. And we have to use run time permissions to request permission instead of user manually going to the settings. Thank you @Bhavya-22 for sharing your thoughts.
