### ISSUE TITLE
Bluetooth connection problem

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#661]
**Issue** :- For bluetooth connection the dialog box is loading but neither it able to connect nor it fails.

**How will I fix this issue** :- I will set a waiting time of 10 seconds for that box after 10 second the box will dismiss box with snackbar message unable to connect.

**I will work on this issue**

**Comment by Bhavya-22** [comment]
PR for this is created
#688

**Comment by Bhavya-22** [comment]
@arvindnegi1 Sir please review it

**Comment by asaikarthikeya** [comment]
Fixed by #752
