### ISSUE TITLE
New Feature:- Navigation View of Others tab

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#665]
**Issue** :- Others section is a tablayout with Dashboard and my tracks instead it will be better if it's a navigation view.

**How will I fix this** :- I will add others values in navigation view along with profile of user(profile photo icon and username) like in most app to make UI better.

![Others_tab](https://user-images.githubusercontent.com/54673703/112222024-320d4400-8c4e-11eb-825a-9b3863a5c921.jpeg)

**I will be working on this feature if it is applicable**

**Comment by Bhavya-22** [comment]
@arvindnegi1 Sir please let me know if I should apply this feature

**Comment by asaikarthikeya** [comment]
Duplicate #578 . Please read the comments of this issue.

**Comment by Bhavya-22** [comment]
But I think navigation view would be more responsive. What if I try my layout for navigation view.
Although I got your point @asaikarthikeya.

**Comment by asaikarthikeya** [comment]
Two weeks of GSoC 2018 have been completely dedicated in shifting the app design from Navigation bar to Bottom navigation bar. Read the advantages of Bottom Navigation bar mentioned and blogs added by 2018 Gsocer. Working on this is like moving back in our development efforts. Thank you for sharing you thoughts @Bhavya-22. Let's wait for @bpross-52n sir response as i have also opened this issue and worked on a design #578

**Comment by Bhavya-22** [comment]
@asaikarthikeya so first I will see why bottom navigation view is preferred over navigation view. Thank you for your reference

**Comment by SebaDro** [comment]
@asaikarthikeya already explained why bottom navigation is preferred. So far, I don't see any need to work on this issue. Anyway, many thanks to @Bhavya-22 for your suggestions.
