### ISSUE TITLE
Click nature for My cars section 

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#666]
**Issue** :- After selecting a radiobutton for my car it doesn't deselect if it clicked again. Also the car not get selected even if we click the car category different than on radiobutton rather it is giving option to select and delete car. Also user cannot delete multiple car at a same time.

**How will I fix this** :- Firstly,on click to car category at any place the car will get selected and on again click it will get deselected.
Secondly, I will implement a onLong click which on click gives a option to delete multiple car category by checkbox selection (which will appear in place of radioButton only in time of deletion).

**I will be working on this issue**

**Comment by asaikarthikeya** [comment]
This enhancement is not required in the current state of the App. Hence i am closing this issue. Feel free to ask if you have any doubts. Thank you.
