### ISSUE TITLE
New feature:- Forget Username and Forget Password option

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#668]
**Issue** :- In enviroCar app there is no system to login if one forget it's username or it's password.

**How will I fix this** :- I will add a verify email authentication (as in register we are taking user email) for both username and password. When verified there we can send a mail regarding forget username and password and let the user know the respective field it forgets.(For initial phase I would like to send password to email too.)

**I will work on this issue if applicable**

**Comment by Bhavya-22** [comment]
@arvindnegi1 @bpross-52n sir please let me know about this

**Comment by asaikarthikeya** [comment]
Please check the comments in this #396 issue. I guess features like Password reset and forgot password would be handled by mentors . Wait for the confirmation before working on this. Thank you.

**Comment by Bhavya-22** [comment]
That's why I tagged the mentors and wrote I will work if applicable as it can disabled or not visible because of some reason.

**Comment by asaikarthikeya** [comment]
I have tagged the issue since it expresses the views of previous mentor who worked on this project. Tagged issue also serves as a point of reference for analyzing this issue. Please refer to old issues before opening new one's.

**Comment by asaikarthikeya** [comment]
Duplicate - #443
