### ISSUE TITLE
LogBook Dialog Box changes

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#669]
**Issue** :- On selecting a particular added fueling the dialog box is showing just delete and cancel option. There is no edit option to edit the type/selected values.

**How will i fix this issue** :- I will provide a edit button in the box which will be redirected to add fueling with defaults entries as selected by user.

![Fueling_DialogBox](https://user-images.githubusercontent.com/54673703/112225126-51a66b80-8c52-11eb-8d23-e1322e0d38a0.jpeg)

**I will be working on this issue**

**Comment by asaikarthikeya** [comment]
First part of issue is implemented by #747 . Edit option is duplicate of #479

**Comment by SebaDro** [comment]
#747 only addresses the layout of dialogs but not the edit feature. So it still needs to be implemented. However, this issue actually is a duplicate of #479 which was posted first. Hence, I will close this issue right now.
