### ISSUE TITLE
Login,Register,Logout options as icons

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#670]
**Issue** :- For login , Register option there is a drop down menu with one item. After login the same is for logout.

**How will i fix this** :- Instead of using dropdown menu i will set them as menu icons which are always visible. Login and register icon if user is logged out and logged out icon if user is logged in which onlong click show what icon represent by a toast message.

![Login_option](https://user-images.githubusercontent.com/54673703/112225851-6cc5ab00-8c53-11eb-994d-bec74d450ed6.jpeg)

![Logout_option](https://user-images.githubusercontent.com/54673703/112225856-6df6d800-8c53-11eb-8e80-9b42cd136344.jpeg)

**I will be working on this issue**

**Comment by asaikarthikeya** [comment]
#429

**Comment by Bhavya-22** [comment]
So why is it open for a year is there something sarthak missed or it's like not to implement icons
@arvindnegi1 sir please let me know about this

**Comment by arvindnegi1** [comment]
@Bhavya-22 Since no PRs has been made and contributor who raised issue is not active. You can work on this but please close this issue and create PR referring to the issue already created. Thanks ;)

**Comment by Bhavya-22** [comment]
Ok sir
