### ISSUE TITLE
Feature: Closing down the typing keyboard by touching the background

### ISSUE THREAD

**Issue by swayamkaul** [enviroCar/enviroCar-app#671]
The keyboard does not close down until back is pressed.
Adding the option to click the anywhere on the background to close the typing keyboard makes the UI more handy and smoothens the experience especially in the UIs where the keyboard is hiding some buttons or text boxes like. 
![Screenshot 2021-03-25 at 3 27 45 AM](https://user-images.githubusercontent.com/43716674/112390088-c1345d80-8d1b-11eb-8fa2-cce4794bc574.png)
![Screenshot 2021-03-25 at 3 25 35 AM](https://user-images.githubusercontent.com/43716674/112390115-cd201f80-8d1b-11eb-991e-6ba79914b87d.png)

Solution: i will add an onClick listener on the background layout that will close the typing keyboard.

**Comment by swayamkaul** [comment]
**I will be working on this issue**

**Comment by cdhiraj40** [comment]
@asaikarthikeya I think HSN/TSN and car attributes fragments still doesn't support this, not sure if this is needed so do tell me if I can work on this :)
(car selection fragment do support this, which only covers the upper part of the screen)
