### ISSUE TITLE
Typo error in help section

### ISSUE THREAD

**Issue by shubh-cmd** [enviroCar/enviroCar-app#677]
when you go to help section and then subsection 2.3, there is some typo, that is in place of OBD-II adapter, it is written ODB-II Adapter.
Apart from 2.3 subsection, some other subsection is also having same typo error

@arvindnegi1 , confirm if I am right!

**I will be working on this if gets confirmation.** Actually i am new to open source so it would be great to start with this issue

**Comment by arvindnegi1** [comment]
you can work on this.
thanks!
