### ISSUE TITLE
Text Pointer not visibility clearly

### ISSUE THREAD

**Issue by BolisettySujith** [enviroCar/enviroCar-app#678]
When the user what's to **log in** or **Register** in the app, the text pointer color merged with the background color and it is not clearly visible. Because of that, some people can't see that where the pointer point's the name, so I want to make the pointer to be visible.

https://user-images.githubusercontent.com/73323807/113332680-20f3bf80-933f-11eb-93f9-fd20407c60e1.mp4

How will I fix the issue: By adding **textCursorDrawable** to  **AppCompatEditText**

@bpross-52n sir, @arvindnegi1  I will work on this issue, as it's my first one.

**Comment by asaikarthikeya** [comment]
Duplicate #603 

Welcome to the community @BolisettySujith. I have worked on this particular issue. PR is not yet reviewed. Thank you :)

**Comment by BolisettySujith** [comment]
@asaikarthikeya thanks for intimating early, no problem I will look for another issue. Thank you :)

**Comment by arvindnegi1** [comment]
@BolisettySujith please close this issue.

**Comment by BolisettySujith** [comment]
@arvindnegi1 ok thank you
