### ISSUE TITLE
New Feature : Adding dark theme to the app

### ISSUE THREAD

**Issue by BolisettySujith** [enviroCar/enviroCar-app#682]
In this app, there is no night mode display so I want to make the app work for the dark mode also.
We know there are so many uses using dark mode.

Eg:
- It Can reduce power usage by a significant amount (depending on the device’s screen technology).
- Improves visibility for users with low vision and those who are sensitive to bright light.
- Makes it easier for anyone to use a device in a low-light environment.

How I will solve:  using **FORCE DARK**

Mr.@bpross-52n I will work on this issue.

**Comment by BolisettySujith** [comment]
@bpross-52n and @arvindnegi1 I had made a pull request for this, PR > #690  also added screenshots for the dark theme can u please review them.

**Comment by asaikarthikeya** [comment]
Duplicate issue #217. I am closing this issue because #217 is first created and marks this as duplicate. Your PR point towards that issue. Feel free to reopen this issue, if you have any doubts. Thank you.
