### ISSUE TITLE
we can add animations in splash screen.

### ISSUE THREAD

**Issue by ojasjain24** [enviroCar/enviroCar-app#683]

**Comment by arvindnegi1** [comment]
Provide some mock-up design.
thanks!

**Comment by ojasjain24** [comment]
https://user-images.githubusercontent.com/59116312/113757190-f3888680-972f-11eb-9991-b13c3552b1c9.mp4

Like this

**Comment by asaikarthikeya** [comment]
@ojasjain24 Currently the app opening time is around 2 seconds. We would like to add a message as donot use the app while driving, which is partially finalized and planning to commit it in the near future. Hence, I close this issue as we are planning to work on this #366. Thank you for suggesting this feature. Feel free to reopen if you have any other doubts. Thank you.
