### ISSUE TITLE
New Feature: Adding a Alert Dialog box with radio buttons in settings to switch between themes.

### ISSUE THREAD

**Issue by BolisettySujith** [enviroCar/enviroCar-app#687]
In issue #682, the app theme will change by changing the theme in the mobile. But there is no option to switch in the app, so I want to add a **Checkbox** in the **General Settings** to switch between the dark and light theme.

If the checkbox is clicked the app theme will turn into a dark theme otherwise it will remain in the light theme.

**Comment by BolisettySujith** [comment]
@bpross-52n sir i will work on this

**Comment by arvindnegi1** [comment]
This is the part of #682 so why new issue here, the previous one is not been created and merged so this can not be new issue or feature rather it is part of #682.
thanks!

**Comment by BolisettySujith** [comment]
@arvindnegi1 Okay. I made a Pr > #690 with screenshots can u please review and suggest changes.
Thank you.

**Comment by asaikarthikeya** [comment]
As @arvindnegi1 has mentioned, This issue is a part of #682. I am closing this issue. Thank you.
