### ISSUE TITLE
Add themed and improved Snackbar

### ISSUE THREAD

**Issue by Akash-Ramjyothi** [enviroCar/enviroCar-app#693]
## Description:

Currently, the android application uses a default Snackbar to display messages. If there was a better themed and styled Snackbar, it would improve the Interface of the app overall and pave way for better customizations in the future if needed.

### Screenshot of currently used Snackbar:
![WhatsApp Image 2021-04-05 at 4 11 14 AM](https://user-images.githubusercontent.com/54114888/114204472-dc87a580-9976-11eb-8f44-9c1e6798f689.jpeg)

## Maybe fixed on #694

**Comment by Mainakdey1** [comment]
Since this issue is still open , can I work on this problem @Akash-Ramjyothi ?
thank you

**Comment by Akash-Ramjyothi** [comment]
@Mainakdey1 I have already fixed the issue and have made a PR for the same which is under review. I would suggest to work on some other open issues.

**Comment by Mainakdey1** [comment]
@Akash-Ramjyothi ok ,thanks for taking the time to reply .
