### ISSUE TITLE
Close enviroCar dialog box Icon

### ISSUE THREAD

**Issue by Akash-Ramjyothi** [enviroCar/enviroCar-app#707]
## Description:

Currently, the Close enviroCar dialog box which is triggered from Others screen seems default. If there was an Icon implemented in it with same as the triggering button while closing the android app, it would improve the interactivity and user interface of the app.

### Screenshot of current Close dialog box:
![WhatsApp Image 2021-04-08 at 12 41 07 AM](https://user-images.githubusercontent.com/54114888/114224209-698a2900-998e-11eb-9067-b4eeafa88729.jpeg)

### Maybe fixed on #708

**Comment by SebaDro** [comment]
Implemented by merge of #747
