### ISSUE TITLE
Delete Entry dialog box Icon

### ISSUE THREAD

**Issue by Akash-Ramjyothi** [enviroCar/enviroCar-app#724]
## Description:

Currently, the Delete Fueling Entry dialog box which is triggered from Logbook screen seems like the default Material Dialog box. If there was an Icon implemented in it, would improve the interactivity and user interface of the app.

## Screenshot of current Dialog Box:
![WhatsApp Image 2021-04-09 at 12 54 22 AM](https://user-images.githubusercontent.com/54114888/114305596-6b6efc00-9af6-11eb-893b-a44a86b99344.jpeg)

Maybe fixed on #725

**Comment by SebaDro** [comment]
Implemented by merge of #747
