### ISSUE TITLE
Fix Add Fueling screen

### ISSUE THREAD

**Issue by Akash-Ramjyothi** [enviroCar/enviroCar-app#728]
## Description:

Currently, only few Input Fields on Add Fueling screen have heading Icons. The rest do not. This causes major inconsistency on the particular screen to users. If all the Input screens have Materialized Icons, it would improve the user interface.

## Screenshot of current Add Fueling screen:
![WhatsApp Image 2021-04-09 at 1 40 50 AM](https://user-images.githubusercontent.com/54114888/114307184-25b53200-9afc-11eb-9294-a43417248779.jpeg)
 
Maybe fixed on #729

**Comment by asaikarthikeya** [comment]
Merged into the master branch!
