### ISSUE TITLE
Car Selection Card view bug in Dashboard fragment 

### ISSUE THREAD

**Issue by Areeb-510** [enviroCar/enviroCar-app#756]
The selected car card view in the dashboard fragment does not get updated when a car is deleted from the car list to show the default text. I am attaching a video to explain the bug in a better way.

https://user-images.githubusercontent.com/77868296/123952497-b4cb3b00-d9c3-11eb-8f95-075b208076d8.mp4

**Comment by asaikarthikeya** [comment]
Duplicate #572

**Comment by SebaDro** [comment]
I will close this issue, since it it a duplicate of #572.
