### ISSUE TITLE
Delete Track dialog content. 

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#767]
![Screenshot_20210722-182302_enviroCar](https://user-images.githubusercontent.com/70392921/126642168-d8582cdb-77c5-4e45-b507-41b8ad9cab5f.jpg)

**Comment by soham-samanta** [comment]
Hello , I'd like to work on this . Can anyone please guide me

**Comment by asaikarthikeya** [comment]
@soham-samanta This issue has been resolved by #774. You can work on any open issue which doesnot has a "done" or "ready " tag ;)
