### ISSUE TITLE
INVALID INPUT- While selecting the car's construction year 

### ISSUE THREAD

**Issue by DhirajChauhan40** [enviroCar/enviroCar-app#791]
**Description**

Steps to reproduce :-
1-Go to My cars,go for select new
2-Select manufacture --> ALFA LANCIA (I)
                        Model --> ALFA 33 KOMBI
      Construction year --> 1988 (from the list shown or manually typing)
It will give invalid input when you add 1988 as the construction year.

**possible correction**
To remove the construction years which are currently not supported by the app

**Comment by DhirajChauhan40** [comment]
https://user-images.githubusercontent.com/75211982/130576304-d3f2b5d4-43db-4174-89ec-b607c28e5d4b_enviroCar.mp4

**Comment by DhirajChauhan40** [comment]
https://user-images.githubusercontent.com/75211982/130576780-2bdfdbd0-df64-40b6-b6a6-44af98a5ae6a.mp4

**Comment by DhirajChauhan40** [comment]
update:After going through other manufacturers i noticed that this error shows for Construction year < 1990 or 1995 
@asaikarthikeya

**Comment by asaikarthikeya** [comment]
@DhirajChauhan40  Yes. It is intentially done so. The users who use the app generally donot use a car which is 30 years old. Hence it shows error.

**Comment by DhirajChauhan40** [comment]
Then that construction year should doesn't show right? or the data comes from manufacturers server and it's directly shown?
