### ISSUE TITLE
Automatically close keyboard after filling a parameter in car selection. 

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#795]
### Description 

While creating a new car, After user succesfully add a HSN/TSN value the keyboard should close automatically. Simialar behaviour is expected when entering all attributes while creating a new car.

**Comment by asaikarthikeya** [comment]
@DhirajChauhan40 You can take this up. This will be good starting point. Feel free ask if you have any doubts. Thanks

**Comment by DhirajChauhan40** [comment]
@asaikarthikeya okayy i will start from tomorrow and will give you updates regularly.

**Comment by DhirajChauhan40** [comment]
@asaikarthikeya i need help implementing it, i have the code for hide keyboard .

my approach was to check if the values are not empty then close the keyboard but I'm not able to implement it.

**Comment by asaikarthikeya** [comment]
> @asaikarthikeya i need help implementing it, i have the code for hide keyboard .
> 
> my approach was to check if the values added by user are not empty then close the keyboard but I'm not able to implement it. (maybe because I didn't know much about AutoCompleteTextView, after reading the documentation about it i am still unable to implement it)

Sure, Mail me your approach and finds at a.saikarthikeya@gmail.com. Lets try to figure this. Thanks.

**Comment by DhirajChauhan40** [comment]
> > @asaikarthikeya i need help implementing it, i have the code for hide keyboard .
> > my approach was to check if the values added by user are not empty then close the keyboard but I'm not able to implement it. (maybe because I didn't know much about AutoCompleteTextView, after reading the documentation about it i am still unable to implement it)
> 
> Sure, Mail me your approach and findings at [a.saikarthikeya@gmail.com](mailto:a.saikarthikeya@gmail.com). Lets try to figure this. Thanks.

sure. Also i have made requested changed in PR #799 you can checkout

**Comment by DhirajChauhan40** [comment]
@asaikarthikeya okay its working woo!
thanks

**Comment by asaikarthikeya** [comment]
PR made for this issue #802

**Comment by cdhiraj40** [comment]
@asaikarthikeya Heyy I am already done with this work and ready to make PR 
you know I  was waiting for the other PR to be done so I can make new

**Comment by cdhiraj40** [comment]
I couldn't make a new PR cause of a branch issue that's why I was waiting for the old PR to be merged
you said its gonna take a while 

> @asaikarthikeya Heyy I am already done with this work and ready to make PR
> you know I was waiting for the other PR to be done so I can make new

**Comment by asaikarthikeya** [comment]
@cdhiraj40 Yes, I know that you were working on this issue. I am unaware that @FabianWessel is working on this issue. The PR made for this issue is not merged yet, May be @SebaDro and @FabianWessel have not looked at this issue and our conversation . Lets wait to hear @SebaDro Sir views about this.

And regarding the opening multiple PR's, You can create multiple branches from the develop and work on each branch separately and create PR's. If you are have doubts regarding the creation of multiple PRs, do mail me i will help you :) thanks.

**Comment by cdhiraj40** [comment]
> @cdhiraj40 Yes, I know that you were working on this issue. I am unaware that @FabianWessel is working on this issue. The PR made for this issue is not merged yet, May be @SebaDro and @FabianWessel have not looked at this issue and our conversation . Lets wait to hear @SebaDro Sir views about this.
> 
> And regarding the opening multiple PR's, You can create multiple branches from the develop and work on each branch separately and create PR's. If you are have doubts regarding the creation of multiple PRs, do mail me i will help you :) thanks.  

okayy okayy a relief, thanks for considering my points.

yes i know about opening multiple PRs but I made a mistake by directly working in my fork's develop branch and I have committed the changes in the old PR so whenever I make a new branch the old commits will come 
to change this either I will have to make a new PR after the old one gets merged(which I have decided) or delete the fork, refork and make the old PR again which I had already done so I didn't go that way

**Comment by cdhiraj40** [comment]
> Hey guys. Sorry, I was not aware of your conversation, so that I asked @FabianWessel to work on this issue. Since I've already reviewed his implementation  I'm looking forward to merge #802.
> 
> However, the `SendLogFileActivity` still does not support closing the keyboard when clicking in the background. Maybe, you can work on this? If you're ok with it, please create a separate issue for it, so that I can close this one. Subsequently, you can create a PR based on the latest developed branch. 

hey @SebaDro it's fine I can try to work on that issue
thanks for the response and suggestion.
you can close the issue :)

**Comment by asaikarthikeya** [comment]
Merged into the master branch!
