### ISSUE TITLE
 ```SendLogFileActivity```  does not support closing the keyboard when clicking in the background.

### ISSUE THREAD

**Issue by cdhiraj40** [enviroCar/enviroCar-app#803]

**Comment by cdhiraj40** [comment]
@SebaDro hey SebaDro as we talked about earlier I would like to work on this issue.

**Comment by SebaDro** [comment]
Great. Feel free to go ahead

**Comment by cdhiraj40** [comment]
@asaikarthikeya I'm done with the code, I will make a new PR as soon as you merge the old PR.

**Comment by cdhiraj40** [comment]
https://user-images.githubusercontent.com/75211982/131890736-2fde0eb7-ade2-45b2-b99a-f2805a83ccf5.mp4

**Comment by SebaDro** [comment]
#802 has just been merged. Feel free to go ahead.

**Comment by cdhiraj40** [comment]
> #802 has just been merged. Feel free to go ahead.

no actually i meant my old PR, i mistakenly started working on develop branch so even if i make new branch, the old commits come so thats why the old PR should get merge

**Comment by SebaDro** [comment]
No need to wait for the old PR for being merged ;-). Just create a separate _fix/name_ branch based on the current develop branch , implement the proposed fix and create a new pull request for it.

**Comment by asaikarthikeya** [comment]
@cdhiraj40 May be you can delete and refork the enviroCar project again. And then create a new branch from the develop and add your changes there. Do ask if you have any doubts :)
