### ISSUE TITLE
Welcome message is shown to the user in Dashboard,  when changing the bottom navigation framgents.

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#805]
Welcome message should be only shown to the user after succesfull login.

**Comment by cdhiraj40** [comment]
Hey @asaikarthikeya I tried this, the reason it keeps on showing is that we are calling the function ``` updateUserLogin ``
again and again in ```onCreateView```
when I commented out the part it only showed once when we open the app (but obv the stats didn't update)
making a new function and trying might help, I'm doing the work if I get it I will make PR if you are okay

**Comment by asaikarthikeya** [comment]
@cdhiraj40 Okay, Feel free to go ahead. Thanks

**Comment by cdhiraj40** [comment]
@asaikarthikeya I have coded that ```snackbar``` only shows the first time when you enter the app
but doing it after logging is I'm not able to because it doesn't go directly to the home screen after logging (intent is not there)

**Comment by cdhiraj40** [comment]
https://user-images.githubusercontent.com/75211982/132101930-81b25832-00df-4afa-8993-e68aa2cea59b.mp4
hope no one hacks me :)

**Comment by asaikarthikeya** [comment]
> @asaikarthikeya I have coded that `snackbar` only shows the every time you enter the app
> but I'm not able to do it after logging the reason can be that it doesn't go directly to the home screen after logging (intent is not there)

Seems like a new bug got added in our develop branch, Are you able to reproduce this @SebaDro sir ?

**Comment by asaikarthikeya** [comment]
@cdhiraj40 I have deleted that comment as the log-in credentials are visible in the screen recording :)

**Comment by cdhiraj40** [comment]
> @cdhiraj40 I have deleted that comment as the log-in credentials are visible in the screen recording :)

nice thanks :)

**Comment by cdhiraj40** [comment]
hey @asaikarthikeya I'm done with this issue (including redirecting to dashboard fragment )if the team is not working I can make PR

**Comment by cdhiraj40** [comment]
> hey @asaikarthikeya I'm done with this issue (including redirecting to dashboard fragment )if the team is not working I can make PR

https://user-images.githubusercontent.com/75211982/132127498-4ee1c208-1a03-4d88-900b-7380ac155007.mp4

**Comment by asaikarthikeya** [comment]
Perfect! Please consider raising the PR. Many thanks for resolving this.🙂

**Comment by cdhiraj40** [comment]
> Perfect! Please consider raising the PR. Many thanks for resolving this.🙂

sure. should i make 2 PRs, one for login intent and other for this issue? or one is fine. ,;-)

**Comment by asaikarthikeya** [comment]
Do it in multiple commits, Its fine if you do it in 1 PR as the number of lines of code is not very big.  Thanks.

**Comment by SebaDro** [comment]
Fixed by dba654c and b71ba2c.

**Comment by asaikarthikeya** [comment]
Merged into the master branch!
