### ISSUE TITLE
Weird ViewPager lifecycle

### ISSUE THREAD

**Issue by SebaDro** [enviroCar/enviroCar-app#807]
**Description**
The ViewPager for managing navigation between the three fragments (`DashboardFragment`, `TrackListPagerFragment` and `OthersFragment`) within the `BaseMainActivity` does not work appropriate. Fragments are not created in the order they should be, although they are shown correctly on the mobile device.

**How to reproduce**
Debug into the application and start the app. You will notice that first `DashboardFragment` and after it `TrackListPagerFragment` will be created, although it has not been selected. When you switch to `TrackListPagerFragment`, `OthersFragment` is created but not displayed on the device. Switching back to `TrackListPagerFragment` results in creating `DashboardFragment`. You can check this behaviour by setting a breakpoint inside the `onCreateView()` methods of the three fragments. You can also notice this behaviour when debugging into `getItem()` of  `PageSlider`, since it does not request the correct fragment position .

**Possible solution**
Since `TrackListPagerFragment` has its own `FragmentStatePagerAdapter` it may lead to inconsistencies by handling both adapters at the same time.

**Comment by pratik2315** [comment]
Hey! I want to work on this issue, Is it still available? 
Thanks.

**Comment by SebaDro** [comment]
Hey @pratik2315. Thanks for your intereset. Actually, we are already working on it. I will inform you about the progress, soon.

**Comment by FabianWessel** [comment]
After checking on this issue it does not seem to be a bug. This behavior is by Android intended. The ViewPager always keeps the neighbouring pages loaded to allow smooth swiping to the next page. Check here for more information: [https://stackoverflow.com/questions/28456719/android-view-pager-oncreateview-getting-called-for-both-fragments](https://stackoverflow.com/questions/28456719/android-view-pager-oncreateview-getting-called-for-both-fragments)

**Comment by SebaDro** [comment]
Great. However, this causes some problems for refreshing the view, since new recorded local tracks are not shown in the local tracks fragment. But for now, I will close this issue.

**Comment by pratik2315** [comment]
Thank you @FabianWessel for the knowledge!
