### ISSUE TITLE
Adding Auto Rotation to the Activities

### ISSUE THREAD

**Issue by cdhiraj40** [enviroCar/enviroCar-app#816]
As of now, nothing happens if a user turns on the screen rotation. It would be good to add this feature as while traveling landscape mode looks better

**Comment by asaikarthikeya** [comment]
Landscape mode is not required at the moment. The use case of the app deals with seeing/observing the track details after the journey not while the journey( not like google maps). Although we have full screen view which is sufficient at this moment. Thanks for sharing you thoughts @cdhiraj40 :)
