### ISSUE TITLE
Add full screen view while track is going on.

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#817]
Add the full screen view of Map while recording a track, Similar to the map view of recorded tracks.

**Comment by asaikarthikeya** [comment]
![Screenshot_20210917-122527_enviroCar](https://user-images.githubusercontent.com/70392921/133738339-b8ad0563-6f6b-485d-8f76-b36a0d73ca25.jpg)

**Comment by cdhiraj40** [comment]
Hey, @asaikarthikeya I have never tracked from the app. Is it necessary to have a OBD-II adapter and connected with the car?  is there a way to do it without (with a simple Bluetooth device) to test?

**Comment by asaikarthikeya** [comment]
Actually we need a OBD. But for testing purpose we have OBD Simulator ( as mentioned in the Readme) and also GPS option in settings.

OBD Simulator:
You would require 2 smart phone to test this out. One mobile should contain the App and other with the Simulator. Both devices should be connected via Bluetooth. Now click start track in the app and you will see the app starts tracking the Journey.

GPS
This is a bit easy way. Go to setting and turn on GPS tracking then start tracking.

**Comment by cdhiraj40** [comment]
> Actually we need a OBD. But for testing purpose we have OBD Simulator ( as mentioned in the Readme) and also GPS option in settings.
> 
> OBD Simulator:
> You would require 2 smart phone to test this out. One mobile should contain the App and other with the Simulator. Both devices should be connected via Bluetooth. Now click start track in the app and you will see the app starts tracking the Journey.
> 
> GPS
> This is a bit easy way. Go to setting and turn on GPS tracking then start tracking.

Thanks for explaining. I will sure try and see if I can work on the issue. :)
