### ISSUE TITLE
profile picture for users

### ISSUE THREAD

**Issue by cdhiraj40** [enviroCar/enviroCar-app#822]
It currently just shows this image, which seems to me like the user is not logged in. Letting users to add/set a profile picture will definitely give a good look to the dashboard.

![Screenshot_2021-09-18-18-17-40-85_47898aacd586656d6f60f8abb18dee77.jpg](https://user-images.githubusercontent.com/75211982/133889294-65128e1c-ec57-4598-9822-fb9ab3dc57ad.jpg)

**Comment by cdhiraj40** [comment]
@asaikarthikeya @SebaDro if you would like this feature, I will work on it. Thanks

**Comment by asaikarthikeya** [comment]
Duplicate #769
