### ISSUE TITLE
Language in Track details is different than the Device's language.

### ISSUE THREAD

**Issue by cdhiraj40** [enviroCar/enviroCar-app#823]
![Screenshot_2021-09-19-13-11-53-08_47898aacd586656d6f60f8abb18dee77.jpg](https://user-images.githubusercontent.com/75211982/133919637-096d1ebd-874b-4514-889b-cadb763c18a1.jpg)

**Comment by cdhiraj40** [comment]
solved one:

![Screenshot_2021-09-19-13-12-35-76_47898aacd586656d6f60f8abb18dee77.jpg](https://user-images.githubusercontent.com/75211982/133919645-98aab7b8-85f5-4b1f-a9cb-b10324cd721a.jpg)

**Comment by cdhiraj40** [comment]
@asaikarthikeya  I will make PR if you approve. Thanks

**Comment by asaikarthikeya** [comment]
@cdhiraj40 You can go ahead. For most of the trival issue you can work on them directly, no need to ask, you can post the PR. Ask only If it is related to UI or some other critical bug/ new feature. Rest all can be worked on directly no need to wait ;-). Thanks

**Comment by cdhiraj40** [comment]
> @cdhiraj40 You can go ahead. For most of the trival issue you can work on them directly, no need to ask, you can post the PR. Ask only If it is related to UI or some other critical bug/ new feature. Rest all can be worked on directly no need to wait ;-). Thanks

okay. I will take care of this. Thanks :)

**Comment by asaikarthikeya** [comment]
Fixed by https://github.com/enviroCar/enviroCar-app/commit/9f830fd3d2a4961bac39089473238e97cd0f34b5

**Comment by asaikarthikeya** [comment]
Merged into the master branch!
