### ISSUE TITLE
Remote track list overlays "No internet" placeholder

### ISSUE THREAD

**Issue by SebaDro** [enviroCar/enviroCar-app#825]
**Description**
The "No internet" placeholder is covered by already downloaded remote tracks.
**How to reproduce**
Record and upload a track with active internet connection. Close the app and disbale internet. Restart the app and visit the remote tracks screen. You will notice, that the remote track will be loaded from local DB but "No internet" placeholder overlays it.
**How to fix**
Maybe, consider only showing a snackbar, indicating that the user is not connected to the internet, if there are remote tracks locally available.

**Comment by SebaDro** [comment]
Fixed by #828

**Comment by asaikarthikeya** [comment]
Merged into the master branch!
