### ISSUE TITLE
Missing Fuel Consumption in GPS-Track Statistics

### ISSUE THREAD

**Issue by FabianWessel** [enviroCar/enviroCar-app#831]
I realised that in the statistics of GPS-Tracks the estimated fuel consumption is missing:

![Screenshot_20210924-112818](https://user-images.githubusercontent.com/88707987/134654421-5c245540-632c-462b-9d5d-5537f18c75aa.png)

Maybe the consumption gets only estimated, if a minimum speed is reached. While testing I was not moving.

**Comment by SebaDro** [comment]
Hey, thanks for reporting this issue. Could you check if this is still a thing when you're moving aorund in GPS mode?

**Comment by asaikarthikeya** [comment]
Merged into the master branch!
