### ISSUE TITLE
Axis Title gets covered by values in Track Statistics

### ISSUE THREAD

**Issue by FabianWessel** [enviroCar/enviroCar-app#832]
Sometimes the values of the axis cover the title of the axis. This can be provoked by creating short tracks of a few seconds.

![Screenshot_20210924-112848](https://user-images.githubusercontent.com/88707987/134656575-e82cbff8-cf65-4c44-b797-11b93b134756.png)

**Comment by SebaDro** [comment]
Fixed by #834
