### ISSUE TITLE
Export of Tracks fails

### ISSUE THREAD

**Issue by FabianWessel** [enviroCar/enviroCar-app#838]
**Description:**
When you try to export a track, the process fails. The App displays the following message: "General Track Error - Please report this issue"

**How to reproduce:**
- Navigate to `My Tracks`
-  Choose a track and select `Export Track`
- The export fails

**Comment by harshit973** [comment]
I want to work on this issue

**Comment by asaikarthikeya** [comment]
@harshit973 If you would like to work on this, Kindly propose a way to solve this. Thank you.
