### ISSUE TITLE
Screen becomes dull/ black shade after adding a new car.

### ISSUE THREAD

**Issue by asaikarthikeya** [enviroCar/enviroCar-app#841]
After a new car is added to my cars by using + sign in the bottom. The screen becomes dull/ a black shade is observed. This black shade disappears after refreshing the fragment. Such behaviour is also observed in logbook.

**Comment by asaikarthikeya** [comment]
@SebaDro You can take this up sir. I think this is due to the animation that is being used while adding a new entry. Thanks :)

**Comment by SebaDro** [comment]
Fixed by #845

**Comment by asaikarthikeya** [comment]
Merged into the master branch!
