### ISSUE TITLE
adding icon to menu's logout/login buttons

### ISSUE THREAD

**Issue by cdhiraj40** [enviroCar/enviroCar-app#851]
Currently the menu in dashboard contains only 1 item so its better to directly show the item rather than click and show 

or to add icon in item and not show directly
![Screenshot_2021-11-04-20-26-50-77_47898aacd586656d6f60f8abb18dee77.jpg](https://user-images.githubusercontent.com/75211982/140337417-8b6aa114-4206-4d9d-a05e-21fe13f66732.jpg)

![Screenshot_2021-11-04-20-26-47-07_47898aacd586656d6f60f8abb18dee77.jpg](https://user-images.githubusercontent.com/75211982/140337441-c1db151a-db73-468e-a8a8-7e3c53df00fe.jpg)

![Screenshot_2021-11-04-21-35-35-38_47898aacd586656d6f60f8abb18dee77.jpg](https://user-images.githubusercontent.com/75211982/140375724-5dc1f076-bcb9-4b18-8cfc-18b43de216f0.jpg)

**Comment by cdhiraj40** [comment]
hey, @asaikarthikeya which one should I go for it?
text and icon or only icon
(as per me both icons are kinda similar so having text with it will be better to understand) Thanks!

**Comment by asaikarthikeya** [comment]
@cdhiraj40 I would prefer to go with only icon. menu is generally prefer if we have 2 or more items. But the problem with icons is, not many are familiar with login and log out icons. May be a toast on long press on the icon might solve this problem. @SebaDro What do you think about this sir?

**Comment by asaikarthikeya** [comment]
Icon can be preferred but the current state of logout/login menu is sufficient.
