### ISSUE TITLE
Make the email address clickable in help(about section) page

### ISSUE THREAD

**Issue by cdhiraj40** [enviroCar/enviroCar-app#852]
The email address is not a link as of now

![Screenshot_2021-11-04-22-49-41-23_47898aacd586656d6f60f8abb18dee77_1.jpg](https://user-images.githubusercontent.com/75211982/140388394-81134c0e-fa96-4fc5-9b79-bd00279f1d04.jpg)

**Comment by asaikarthikeya** [comment]
Duplicate #457

**Comment by cdhiraj40** [comment]
> Duplicate #457 

hey its different part of help section

**Comment by asaikarthikeya** [comment]
Oops, Sorry. You can take reference from #788. I will merge it.

**Comment by cdhiraj40** [comment]
> Oops, Sorry. You can take reference from #788. I will merge it. 

its fine :)
I actually took reference from it only, you can sure check :)

**Comment by asaikarthikeya** [comment]
Just a small change is required, Do update the PR and squash commits. I will merge it today. No worries. Thanks
