### ISSUE TITLE
After deleting cars, if 1 car is remaining it doesnt automatically get selected 

### ISSUE THREAD

**Issue by cdhiraj40** [enviroCar/enviroCar-app#858]
The way car get automatically selected, when no cars are there
It will be good if it gets automatically selected, when only one car is left after deleting other cars

https://user-images.githubusercontent.com/75211982/142438502-9bd17c7b-ce05-4e21-856f-ab15e58770f7.mp4

feature implementation screen recording 

https://user-images.githubusercontent.com/75211982/142440029-e4b4d88d-cdfd-42dc-8882-beba747922ce.mp4

**Comment by asaikarthikeya** [comment]
@cdhiraj40 When there is only 1 car created, automatic selection it is forced because users next step would be to selecting the car. But this is not the case with deletion. ;)
