### ISSUE TITLE
BUG while deleting the car, if no options selected

### ISSUE THREAD

**Issue by cdhiraj40** [enviroCar/enviroCar-app#867]
There is a bug when you do not select an option in the middle of deleting the car, and the radio button unchecks.

possible solution:
uncheck the radio button only when the car is getting deleted 

https://user-images.githubusercontent.com/75211982/143727223-19126b72-7575-490c-bbf4-47e45aff52a1.mp4

**Comment by cdhiraj40** [comment]
I am working on this

**Comment by SebaDro** [comment]
Fixed by #868
