### ISSUE TITLE
The side menubar can be replaced with LOGIN/REGISTER button as it contains just one option

### ISSUE THREAD

**Issue by pree-T** [enviroCar/enviroCar-app#880]
The side menubar contains just one option of login and sign up .Replacing it with login or register button will look better
![1641368345318](https://user-images.githubusercontent.com/47977131/148178857-05feb9b8-8e19-4f0c-88a8-1b9744aa86bd.jpg)
.

**Comment by SebaDro** [comment]
I will close this issue because it does not fullfill our [contributing guidelines](https://github.com/enviroCar/enviroCar-app/blob/master/CONTRIBUTING.md).
