### ISSUE TITLE
Provide mapbox installation information

### ISSUE THREAD

**Issue by SebaDro** [enviroCar/enviroCar-app#886]
**Description**
Since the JCenter repository will be shut down, some dependencies for the mapbox SDK won't be pulled automatically anymore. Hence, with 88023a4b we changed to the mapbox Maven repository in order to resolve these dependencies. However, this strategy requires a mapbox account and placing credentials within local gradle.properties. The required steps for getting started should be documented within the README.md. For further details, have a  look at: https://docs.mapbox.com/android/maps/guides/install/

**Branches**
master, develop

**Comment by cdhiraj40** [comment]
@SebaDro I can give it a try to this, as many contributors will come soon. It will be really helpful for them :)

**Comment by SebaDro** [comment]
Fixed by #889
