### ISSUE TITLE
MapBox library - Build failure

### ISSUE THREAD

**Issue by Akash-Ramjyothi** [enviroCar/enviroCar-app#895]
## Description:
Facing the below Build Failure while trying to Build the android app and to run it locally. Seems to be some dependency issue regarding Mapbox dependency.

### Screenshot:
![Screenshot 2022-03-26 at 11 32 27 PM](https://user-images.githubusercontent.com/54114888/160251782-ff790b58-cd45-4c87-8368-c72b36349da2.png)

**Comment by Akash-Ramjyothi** [comment]
@SebaDro @bpross-52n @asaikarthikeya @arvindnegi1 please help me with this issue. Due to this I am unable to build locally and to contribute to the project.

**Comment by cdhiraj40** [comment]
@Akash-Ramjyothi first of all if the Gradle is in offline mode then do make toggle it off 
![image](https://user-images.githubusercontent.com/75211982/160251888-0aa3be28-465d-4764-9ed3-0d2f7097b1bf.png)

and look at this [PR](https://github.com/enviroCar/enviroCar-app/pull/889), I have added on how one can create an account on Mapbox and build the project :)

@SebaDro @asaikarthikeya, could you look at the [PR](https://github.com/enviroCar/enviroCar-app/pull/889)? I think it will help other contributors a lot.

**Comment by Akash-Ramjyothi** [comment]
@cdhiraj40 thank you so much for helping, but unfortunately the Issue still persists. I have Toggled offline and have pasted the MAPBOX Token in gradle.properties. I am sharing the screenshot too. Can you please help me with it?

![Screenshot 2022-03-27 at 12 16 20 AM](https://user-images.githubusercontent.com/54114888/160253041-3d640fa5-dfb6-4437-a00e-e01ea1c616f2.png)

**Comment by cdhiraj40** [comment]
@Akash-Ramjyothi please delete the screenshot as it has your API_KEY and about the error, I was able to see that you had written 2 backticks before MAPBOX_DOWNLOADS_TOKEN, which should not be there. 
![image](https://user-images.githubusercontent.com/75211982/160253608-3bdf95f1-40f2-4a65-9467-1dff6ba0f174.png)
If you will see readme as a simple text file then you will see those 2 back ticks but in preview those backticks make
`` MAPBOX_DOWNLOADS_TOKEN``looks like this.

**Comment by Akash-Ramjyothi** [comment]
Hey it worked. Thank you so much @cdhiraj40 for the immediate help . It really means a lot to me.
