### ISSUE TITLE
PNG Icon in Car Selection Activity

### ISSUE THREAD

**Issue by Akash-Ramjyothi** [enviroCar/enviroCar-app#898]
## Description:
In the Car Selection Activity, by default there exists an Icon which is in PNG (Portable Network Graphics) format. This might cause scalability problems on larger screens like android Tablets were to be used. If these were replaced with a Materialistic SVG (Scalable Vector Graphics) resource file, it would be better.

## Screenshot of current Car Selection Activity:
<img src="https://user-images.githubusercontent.com/54114888/161425725-c3c4aec1-dd79-4947-8642-e9ce69495950.jpeg" width="300">

## Maybe fixed on: #899.

**Comment by SebaDro** [comment]
Please, check if there is actually an issue with larger screens. For now, I will close the issue. If larger screens cause resolution problems after all, you can open this issue, again.
