### ISSUE TITLE
UX in Report Issue screen

### ISSUE THREAD

**Issue by Akash-Ramjyothi** [enviroCar/enviroCar-app#905]
## Description:
In the Report Issue screen which is accessed from the Others section, has a flaw. For users to report any issue, they first have to fill in the details and then Scroll to the Bottom to find and Send Report. If this UX was improved such that Users need not scroll and can just directly click on the Send Report button after filling the details, it would improve the UX of the application and very convenient for users to Report issues.

## Screenshot of current Report Issue screen:
<img src="https://user-images.githubusercontent.com/54114888/161429857-f0fabb6e-0a10-4183-b48a-afd6d75450f1.jpeg" width="300">

## Maybe fixed on: #906.

**Comment by SebaDro** [comment]
If we do so, people tend to directly click on the send button without describing the problem. Hence, this is an UI/UX enhancement which is not strictly necessary.
