### ISSUE TITLE
App crashes when we stop the track before the track starts recording

### ISSUE THREAD

**Issue by anamansari062** [enviroCar/enviroCar-app#908]
## Issue 
In Develop branch, When a user stops the track before the track  starts recording or the timer starts, The app crashes

## Step to reproduce
1. Go to GPS mode
2. Click on start tracking
3. Immediately after the recording screen comes up, click on stop button
4. Click yes for the dialog box.

## Possible Solution
1. We can make the stop button unclickable untill the recording starts
2. Or we can check before exiting that recording is started or not

https://user-images.githubusercontent.com/85510030/163064806-dcd0faad-7fcb-4e05-a7e8-d09c76ec4764.mov

**Comment by SebaDro** [comment]
Fixed by #909 and will be closed as soon as it has been merged into the master.
