### ISSUE TITLE
Gradle Build failure

### ISSUE THREAD

**Issue by Akash-Ramjyothi** [enviroCar/enviroCar-app#917]
## Description:

Facing the below Build failure due to unknown reasons. Was working fine until a few days ago, where this error occurred. Also tried to fix it by reseting MAPBOX credentials and cloning it again, but did not work.

### Screenshot:

![WhatsApp Image 2022-06-06 at 7 56 31 PM](https://user-images.githubusercontent.com/54114888/172453173-3978e2c0-b8b8-4a31-976c-e9b5e6ad3063.jpeg)

**Comment by SebaDro** [comment]
Hi @Akash-Ramjyothi .
Please, describe your problem a little bit more in detail. In which branch does this issue occur? What is you build command?

I'm pretty sure, that you're facing an issue with your local IDE settings. Please, check it by exeucting `gradlew assembleDebug` from a terminal. If it runs without any failures, your have to check your IDE settings.

**Comment by Akash-Ramjyothi** [comment]
@SebaDro sir the issue is resolved. It was not an issue with the branch or any command. It was a problem with my JDK configuration, which I fixed it. **Thank you so much for the guidance,** as you said, this was an issue with my local IDE.

**Comment by SebaDro** [comment]
Great to hear. Therefore, I will close this issue.
