### ISSUE TITLE
Improve Materialization in Sign-In Activity

### ISSUE THREAD

**Issue by Akash-Ramjyothi** [enviroCar/enviroCar-app#931]
## Description:
Even though the Sign-In Activity of the app uses `TextInputLayout`, the EditText does not seems to be materialized when compared to other Google android apps.  Also it is using the default `AppCompatEditText` which can be changed to `material.TextInputEditText`.

### Maybe fixed by: #932 .

**Comment by asaikarthikeya** [comment]
Duplicate #796
