### ISSUE TITLE
Showing ProgressBar or ProgressDialog at the time of pairing other device with bluetooth

### ISSUE THREAD

**Issue by SB2318** [enviroCar/enviroCar-app#969]
### Current Situation:

https://user-images.githubusercontent.com/87614560/206856789-de0d9d29-33a9-4f7b-ba80-eb60f543c561.mp4

So, we see that when pairing has started nothing will happen for some time. It may create confusion for the user. 

### How can we improve it?

Instead of this, if we show a ProgressDialog like some other cases in the app or show a progress bar, I think it may be more user-friendly.

If possible, then I want to work on this issue with the guidance of the maintainers.

**Comment by oyehanif** [comment]
Hello Sir. This issue is available i want to work on this issue

**Comment by siddhant-clearcals** [comment]
sir i want to work on this issue?

**Comment by suraj5feb** [comment]
sir want to work on this issue.

**Comment by SanjaySargam** [comment]
I would love to work on this issue

**Comment by SebaDro** [comment]
Fixed with 1929a8b
