### ISSUE TITLE
[Bug | feature/voicecommand] Cannot resolve method makeIsDashboardFragmentFalse()

### ISSUE THREAD

**Issue by devAyushDubey** [enviroCar/enviroCar-app#979]
**Describe the bug**
While setting up the project for the first time with the `feature/voicecommand` branch, build failed due to this error

**To Reproduce**
1. Checkout `feature/voicecommand` branch.
2. Build the project.

**Expected behavior**
Build should complete without any errors.

**Screenshots**
![Screenshot (1013)](https://user-images.githubusercontent.com/33064931/223450476-922f600c-4c08-4d4d-a84d-9bea2ce6d9ff.png)

**Comment by cdhiraj40** [comment]
Thanks for reporting. Checking on this!

**Comment by SebaDro** [comment]
Have been fixed as part of #991
