### ISSUE TITLE
[Bug | feature/voicecommand] Car Selection command does not work after activity change

### ISSUE THREAD

**Issue by devAyushDubey** [enviroCar/enviroCar-app#986]
**Describe the bug:**

Out of the 3 functional commands that the enviroCar voicecommand project currently supports, one of them is Car Selection.
The basic flow of the car selection voice command is:

![Screenshot (1034)](https://user-images.githubusercontent.com/33064931/229187815-7c78f1c7-58b8-4520-935d-fafea539e1d1.png)

If we follow the flow chart and [ this video](https://youtu.be/9mvJlamtR8A) by @cdhiraj40 , we encounter something like this:

https://user-images.githubusercontent.com/33064931/229186912-aeaeb0b0-6ec9-4031-95fc-7f111064305b.mp4

### The console looks like:
![Screenshot (1026)](https://user-images.githubusercontent.com/33064931/229187405-6b549ed8-ba48-4e97-9c13-74f74de2fa25.png)
---
![Screenshot (1027)](https://user-images.githubusercontent.com/33064931/229188749-b1546816-ab16-4081-a48e-c8a6a008d742.png)

**To Reproduce:**

- Checkout feature/voicecommand branch.
- Build the project.
- Install or run on a device
- On the dashboard fragment, trigger enviroBot by saying `enviroCar listen`
- Once the bot is triggered say `Select a car`, bot will navigate you to CarSelectionActivity
- Once in CarSelectionActivity trigger the bot again and say `Select a car` again

**Expected behavior:**
    The bot should be able to recognize the speech and send an API request for intent recognition.

---

**Comment by Yash12Bansal** [comment]
hello @devAyushDubey @SebaDro 
asssign this issue to me I would like to work on it

**Comment by devAyushDubey** [comment]
Hey @Yash12Bansal , there's already #987 open for this issue, you may explore other issues or create one if find something.

**Comment by SebaDro** [comment]
Fixed as part of #995
